// Package golang generates Go code from XPB schemas.
package golang

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/ElecTwix/xpb/pkg/ast"
	"github.com/ElecTwix/xpb/pkg/codegen/common"
	"github.com/ElecTwix/xpb/pkg/wire"
)

// Optional-field representation styles for Options.OptionalStyle.
const (
	// OptionalValue represents optional scalar/string/bytes/enum fields as a
	// value field plus a generated Has<Field> bool. This avoids the
	// per-present-field pointer-boxing heap allocation that *T optionals incur
	// on decode, and is the default (an empty OptionalStyle resolves to it).
	OptionalValue = "value"
	// OptionalPointer represents optional scalar/string/bytes/enum fields as
	// *T, so nil distinguishes "absent" from a zero value. This is the explicit
	// opt-out from the value default. Non-enum message optionals are always *T
	// regardless of this setting.
	OptionalPointer = "pointer"
)

// Options controls Go code generation.
//
// The zero value (Options{}) selects the fast defaults: value-style optionals
// (value field + Has<Field> bool, no per-present-field pointer box on decode)
// and zero-copy bytes decode (the decoded []byte aliases the input buffer). The
// fields below are framed as explicit opt-outs so Options{} = fast path:
//
//   - OptionalStyle: empty resolves to OptionalValue; set OptionalPointer to opt
//     out to *T optionals.
//   - SafeBytes: false (the zero value) decodes bytes by aliasing the input
//     buffer (zero-copy); set true to opt out to a copying decode.
type Options struct {
	// OptionalStyle selects how optional scalar/string/bytes/enum fields are
	// represented: OptionalValue (the default; an empty string resolves to it)
	// or OptionalPointer (the opt-out *T). Non-enum message optionals are
	// always *T regardless of this setting, since the pointer is the natural
	// absence marker and decode allocates the nested struct anyway.
	OptionalStyle string
	// SafeBytes opts OUT of the zero-copy bytes default. When false (the zero
	// value) bytes fields decode by aliasing the decoder's input buffer
	// (ReadBytesUnsafe) — fast, but the decoded []byte stays valid only while
	// the source buffer is unmodified and alive. When true, bytes decode by
	// copying (ReadBytes), so the decoded slice owns its memory.
	SafeBytes bool
}

// resolvedOptionalStyle returns the effective optional style, resolving the
// empty/zero OptionalStyle to the OptionalValue default.
func (g *Generator) resolvedOptionalStyle() string {
	if g.opts.OptionalStyle == "" {
		return OptionalValue
	}
	return g.opts.OptionalStyle
}

// Generator generates Go code from an AST.
type Generator struct {
	buf   bytes.Buffer
	enums map[string]bool // Track enum names for resolution
	opts  Options
}

// Generate generates Go code for the given file AST using default options.
func Generate(file *ast.File) ([]byte, error) {
	return GenerateWithOptions(file, Options{})
}

// GenerateWithOptions generates Go code for the given file AST using the
// supplied options.
func GenerateWithOptions(file *ast.File, opts Options) ([]byte, error) {
	g := &Generator{
		enums: make(map[string]bool),
		opts:  opts,
	}
	return g.generate(file)
}

// valueOptional reports whether field should use the value+Has<Field>
// representation rather than a *T pointer. Only optional scalar/string/bytes/
// enum fields qualify; non-enum message optionals always stay pointers.
func (g *Generator) valueOptional(field *ast.Field) bool {
	if g.resolvedOptionalStyle() != OptionalValue || !field.Optional {
		return false
	}
	if field.Type.Kind == ast.TypeMessage && !g.isEnumType(field.Type) {
		return false
	}
	return true
}

// bytesReadCall returns the stateless cursor expression for reading a bytes
// field, honoring the SafeBytes opt-out. The expression yields
// `(value, newPos, error)` and takes (data, pos) as the cursor. The default
// (SafeBytes false) is the zero-copy ReadBytesUnsafeAt that aliases the input
// buffer; SafeBytes true opts out to the copying ReadBytesAt.
func (g *Generator) bytesReadCall() string {
	if g.opts.SafeBytes {
		return "xpb.ReadBytesAt(data, pos)"
	}
	return "xpb.ReadBytesUnsafeAt(data, pos)"
}

func (g *Generator) generate(file *ast.File) ([]byte, error) {
	g.buf.Reset()

	// Build enum set for type resolution
	for _, enum := range file.Enums {
		g.enums[enum.Name] = true
	}

	pkg := file.Package
	if pkg == "" {
		pkg = "main"
	}
	g.printf("// Code generated by xpbc. DO NOT EDIT.\n")
	g.printf("package %s\n\n", pkg)

	g.printf("import (\n")
	g.printf("\t\"github.com/ElecTwix/xpb/runtime/go/xpb\"\n")
	g.printf(")\n\n")

	g.printf("var _ = xpb.NewEncoder\n\n")

	// Generate enums
	for _, enum := range file.Enums {
		g.generateEnum(enum)
	}

	// Generate messages
	for _, msg := range file.Messages {
		if err := g.generateMessage(msg); err != nil {
			return nil, err
		}
	}

	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		return g.buf.Bytes(), fmt.Errorf("format error: %w", err)
	}
	return src, nil
}

func (g *Generator) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) generateEnum(enum *ast.Enum) {
	name := enum.Name
	g.printf("// %s is an enum type.\n", name)
	g.printf("type %s int32\n\n", name)
	g.printf("const (\n")
	for _, v := range enum.Values {
		g.printf("\t%s_%s %s = %d\n", name, v.Name, name, v.Number)
	}
	g.printf(")\n\n")

	g.printf("func (e %s) String() string {\n", name)
	g.printf("\tswitch e {\n")
	for _, v := range enum.Values {
		g.printf("\tcase %s_%s:\n", name, v.Name)
		g.printf("\t\treturn \"%s\"\n", v.Name)
	}
	g.printf("\tdefault:\n")
	g.printf("\t\treturn \"UNKNOWN\"\n")
	g.printf("\t}\n")
	g.printf("}\n\n")
}

func (g *Generator) generateMessage(msg *ast.Message) error {
	name := msg.Name

	// Struct
	g.printf("// %s is a generated XPB message.\n", name)
	g.printf("type %s struct {\n", name)
	for _, field := range msg.Fields {
		goType := g.goTypeName(field)
		g.printf("\t%s %s\n", toCamelCase(field.Name), goType)
		if g.valueOptional(field) {
			g.printf("\tHas%s bool\n", toCamelCase(field.Name))
		}
	}
	g.printf("}\n\n")

	// Marshal - V2: no tags, fields in order. Encode threads a register-local
	// `buf` slice through the stateless xpb.Append*To helpers instead of
	// load/storing the Encoder.buf struct field on every field. Marshal starts
	// from a fresh encoder of the estimated capacity, binds its buffer to the
	// local, grows the local once by the fixed-size lower bound, appends each
	// field into the local, then writes the local back to enc exactly once. This
	// is the symmetric encode counterpart of Phase 1's local decode cursor; the
	// wire bytes are byte-identical to the stateful Encoder.
	g.printf("func (m *%s) Marshal() ([]byte, error) {\n", name)
	g.printf("\tenc := xpb.NewEncoder(%d)\n", estimateSize(msg))
	g.generateMarshalBody(msg)
	g.printf("\treturn enc.Bytes(), nil\n")
	g.printf("}\n\n")

	// MarshalTo: same local-buffer pattern, but the local is bound from the
	// passed encoder's buffer (preserving append-to-existing semantics) and
	// written back to it once. Pooling is preserved: a pooled encoder is Reset
	// before MarshalTo, so the local starts empty in the steady-state path.
	g.printf("func (m *%s) MarshalTo(enc *xpb.Encoder) {\n", name)
	g.generateMarshalBody(msg)
	g.printf("}\n\n")

	// Unmarshal - V2: no tags, read fields in order.
	// The depth-cap helper unmarshalAt is unexported on purpose: xpbc emits
	// one Go package per .xpb file and the schema grammar has no `import`
	// directive (see pkg/parser/parser.go), so every nested call is intra-
	// package. If cross-package message references are ever added, this
	// helper must be promoted to UnmarshalAt or the depth must be threaded
	// some other way.
	g.printf("func (m *%s) Unmarshal(data []byte) error {\n", name)
	g.printf("\treturn m.unmarshalAt(data, 0)\n")
	g.printf("}\n\n")

	g.printf("func (m *%s) unmarshalAt(data []byte, depth int) error {\n", name)
	g.printf("\tif depth > xpb.MaxDecodeDepth { return xpb.ErrMaxDepthExceeded }\n")
	if len(msg.Fields) == 0 {
		// A message with no fields decodes nothing; declaring a cursor would
		// leave `pos` (and `data`) unused, which Go rejects at compile time.
		g.printf("\t_ = data\n")
	} else {
		// Decode threads a register-local int cursor (`pos`) through the
		// stateless xpb.*At helpers instead of carrying it in a Decoder struct
		// field. Centralized bounds/compact-length/array-count logic stays in
		// the runtime helpers; the generated body just advances the cursor. The
		// function-scoped `pos`/`err` are reassigned (=) inside the per-field
		// blocks so the cursor is shared across fields rather than shadowed.
		g.printf("\tpos := 0\n")
		groups, coalesced := g.fieldRuns(msg)
		// The function-scoped `err` is only needed by the per-field decode path
		// (the *At helpers return an error). A message whose fields are entirely
		// one coalesced fixed-width run reads through xpb.EnsureRunAt + the
		// unchecked Run*At readers and a block-local `rerr`, so a `var err error`
		// here would be declared-and-unused — a hard Go compile error. Only emit
		// it when at least one non-coalesced group exists.
		hasPerField := false
		for _, c := range coalesced {
			if !c {
				hasPerField = true
				break
			}
		}
		if hasPerField {
			g.printf("\tvar err error\n")
		}
		for gi, group := range groups {
			if coalesced[gi] {
				g.generateRunDecode(group)
				continue
			}
			for _, field := range group {
				g.generateFieldDecode(field)
			}
		}
	}
	g.printf("\treturn nil\n")
	g.printf("}\n\n")

	return nil
}

// isEnumType checks if the type name refers to an enum
func (g *Generator) isEnumType(t ast.FieldType) bool {
	if t.Kind == ast.TypeMessage && g.enums[t.Message] {
		return true
	}
	return t.Kind == ast.TypeEnum
}

// generateMarshalBody emits the shared body of Marshal and MarshalTo: bind a
// register-local `buf` from the encoder, grow it once by the message's
// fixed-size lower bound, append every field into the local via the stateless
// xpb.Append*To helpers, then write the local back to enc exactly once. An
// empty message just rebinds and writes back the (unchanged) buffer.
func (g *Generator) generateMarshalBody(msg *ast.Message) {
	g.printf("\tbuf := enc.Buf()\n")
	if lb := g.fixedSizeLowerBound(msg); lb > 0 {
		// Grow the local once up front so the per-field appends do not each
		// re-check capacity. slices.Grow is a single bounds/grow decision; the
		// fixed-width lower bound never over-allocates past what those fields
		// need, so variable-length fields still append normally afterwards.
		g.printf("\tbuf = xpb.GrowBuf(buf, %d)\n", lb)
	}
	groups, coalesced := g.fieldRuns(msg)
	for gi, group := range groups {
		if coalesced[gi] {
			g.generateRunEncode(group)
			continue
		}
		for _, field := range group {
			g.generateFieldEncode(field)
		}
	}
	g.printf("\tenc.SetBuf(buf)\n")
}

func (g *Generator) generateFieldEncode(field *ast.Field) {
	fieldName := toCamelCase(field.Name)
	isEnum := g.isEnumType(field.Type)

	// Optional fields carry a 1-byte presence flag (see docs/WIRE_FORMAT.md):
	// 0x01 + value when present, 0x00 (and nothing more) when absent. Optional
	// is only valid on scalar/string/bytes/enum/message fields — never on
	// repeated/map, which already carry counts — so the repeated/map branches
	// below are unreachable when field.Optional is set.
	if field.Optional {
		if field.Type.Kind == ast.TypeMessage && !isEnum {
			// Nested message optionals are *T already. Emit the presence
			// byte, then the message body only when non-nil.
			g.printf("\tbuf = xpb.AppendBoolTo(buf, m.%s != nil)\n", fieldName)
			g.printf("\tif m.%s != nil {\n", fieldName)
			g.generateScalarEncode("m."+fieldName, field.Type, "\t\t", isEnum)
			g.printf("\t}\n")
			return
		}
		if g.valueOptional(field) {
			// Value style: presence comes from the Has<Field> bool and the
			// value is used directly (no pointer deref).
			g.printf("\tbuf = xpb.AppendBoolTo(buf, m.Has%s)\n", fieldName)
			g.printf("\tif m.Has%s {\n", fieldName)
			g.generateScalarEncode("m."+fieldName, field.Type, "\t\t", isEnum)
			g.printf("\t}\n")
			return
		}
		// Scalar/string/bytes/enum optionals are *T pointers; deref the value
		// after the presence byte.
		g.printf("\tbuf = xpb.AppendBoolTo(buf, m.%s != nil)\n", fieldName)
		g.printf("\tif m.%s != nil {\n", fieldName)
		g.generateScalarEncode("*m."+fieldName, field.Type, "\t\t", isEnum)
		g.printf("\t}\n")
		return
	}

	// Handle repeated fields - V2: write count then elements
	if field.Repeated {
		g.printf("\tbuf = xpb.AppendInt32To(buf, int32(len(m.%s)))\n", fieldName)
		g.printf("\tfor _, v := range m.%s {\n", fieldName)
		g.generateScalarEncode("v", field.Type, "\t\t", isEnum)
		g.printf("\t}\n")
		return
	}

	// Handle map fields - V2: write count then key-value pairs
	if field.Type.Kind == ast.TypeMap {
		g.printf("\tbuf = xpb.AppendInt32To(buf, int32(len(m.%s)))\n", fieldName)
		g.printf("\tfor k, v := range m.%s {\n", fieldName)
		g.generateScalarEncode("k", *field.Type.KeyType, "\t\t", false)
		g.generateScalarEncode("v", *field.Type.ValType, "\t\t", g.isEnumType(*field.Type.ValType))
		g.printf("\t}\n")
		return
	}

	// Regular field - V2: no tags
	g.generateScalarEncode("m."+fieldName, field.Type, "\t", isEnum)
}

// generateScalarEncode appends one scalar/string/bytes/enum/message value into
// the register-local `buf` via the stateless xpb.Append*To helpers, reassigning
// buf with the grown slice each time.
func (g *Generator) generateScalarEncode(varName string, t ast.FieldType, indent string, isEnum bool) {
	if isEnum || t.Kind == ast.TypeEnum {
		g.printf("%sbuf = xpb.AppendInt32To(buf, int32(%s))\n", indent, varName)
		return
	}

	switch t.Kind {
	case ast.TypeBool:
		g.printf("%sbuf = xpb.AppendBoolTo(buf, %s)\n", indent, varName)
	case ast.TypeInt32:
		g.printf("%sbuf = xpb.AppendInt32To(buf, %s)\n", indent, varName)
	case ast.TypeInt64:
		g.printf("%sbuf = xpb.AppendInt64To(buf, %s)\n", indent, varName)
	case ast.TypeUint32:
		g.printf("%sbuf = xpb.AppendUint32To(buf, %s)\n", indent, varName)
	case ast.TypeUint64:
		g.printf("%sbuf = xpb.AppendUint64To(buf, %s)\n", indent, varName)
	case ast.TypeFloat32:
		g.printf("%sbuf = xpb.AppendFloat32To(buf, %s)\n", indent, varName)
	case ast.TypeFloat64:
		g.printf("%sbuf = xpb.AppendFloat64To(buf, %s)\n", indent, varName)
	case ast.TypeString:
		g.printf("%sbuf = xpb.AppendStringTo(buf, %s)\n", indent, varName)
	case ast.TypeBytes:
		g.printf("%sbuf = xpb.AppendBytesTo(buf, %s)\n", indent, varName)
	case ast.TypeMessage:
		// Nested message fields are represented as Go pointers, so the
		// value can be nil — either an absent optional field or a
		// nil entry inside a repeated/map slice. Calling MarshalTo on
		// a nil pointer would panic; instead, write a 0-length envelope.
		// This is the symmetric counterpart of the decode-side guard
		// that skips unmarshalAt on `len(data) > 0`. The nested message is
		// encoded into its own pooled encoder (whose own MarshalTo uses the
		// local-buffer pattern), then its bytes are appended as a
		// length-prefixed envelope into the parent's local buf.
		g.printf("%s{\n", indent)
		g.printf("%s\tnestedEnc := xpb.GetEncoder()\n", indent)
		g.printf("%s\tif %s != nil { %s.MarshalTo(nestedEnc) }\n", indent, varName, varName)
		g.printf("%s\tbuf = xpb.AppendMessageTo(buf, nestedEnc.Bytes())\n", indent)
		g.printf("%s\txpb.PutEncoder(nestedEnc)\n", indent)
		g.printf("%s}\n", indent)
	}
}

func (g *Generator) generateFieldDecode(field *ast.Field) {
	fieldName := toCamelCase(field.Name)
	isEnum := g.isEnumType(field.Type)

	// Optional fields: read the 1-byte presence flag first. On false, leave
	// the (nil) pointer as-is and consume nothing more, so the next field
	// decodes correctly. On true, read the value and store its address. The
	// cursor (pos) and err are the function-scoped variables, reassigned with
	// = so the cursor advances across fields.
	if field.Optional {
		g.printf("\t{\n")
		g.printf("\t\tvar present bool\n")
		g.printf("\t\tpresent, pos, err = xpb.ReadBoolAt(data, pos)\n")
		g.printf("\t\tif err != nil { return err }\n")
		g.printf("\t\tif present {\n")
		if field.Type.Kind == ast.TypeMessage && !isEnum {
			// Nested message optional: *T. A present message is always a
			// non-empty envelope (it carries at least its own fields, or a
			// 0-length envelope which we still materialize since presence
			// said so). Read the length-prefixed envelope via the cursor,
			// then recurse with depth+1.
			g.printf("\t\t\tvar mb []byte\n")
			g.printf("\t\t\tmb, pos, err = xpb.ReadMessageBytesAt(data, pos)\n")
			g.printf("\t\t\tif err != nil { return err }\n")
			g.printf("\t\t\tm.%s = &%s{}\n", fieldName, field.Type.Message)
			g.printf("\t\t\tif err := m.%s.unmarshalAt(mb, depth+1); err != nil { return err }\n", fieldName)
		} else if g.valueOptional(field) {
			// Value style: store the decoded value and flip the Has<Field>
			// bool. No pointer is taken, so no per-field boxing allocation.
			if isEnum {
				g.printf("\t\t\tvar v int32\n")
				g.printf("\t\t\tv, pos, err = xpb.ReadInt32At(data, pos)\n")
				g.printf("\t\t\tif err != nil { return err }\n")
				g.printf("\t\t\tm.%s = %s(v)\n", fieldName, field.Type.Message)
			} else {
				g.printf("\t\t\tvar v %s\n", g.goBaseTypeName(field.Type))
				g.printf("\t\t\tv, pos, err = %s\n", g.scalarReadCall(field.Type))
				g.printf("\t\t\tif err != nil { return err }\n")
				g.printf("\t\t\tm.%s = v\n", fieldName)
			}
			g.printf("\t\t\tm.Has%s = true\n", fieldName)
		} else if isEnum {
			g.printf("\t\t\tvar v int32\n")
			g.printf("\t\t\tv, pos, err = xpb.ReadInt32At(data, pos)\n")
			g.printf("\t\t\tif err != nil { return err }\n")
			g.printf("\t\t\tev := %s(v)\n", field.Type.Message)
			g.printf("\t\t\tm.%s = &ev\n", fieldName)
		} else {
			g.printf("\t\t\tvar v %s\n", g.goBaseTypeName(field.Type))
			g.printf("\t\t\tv, pos, err = %s\n", g.scalarReadCall(field.Type))
			g.printf("\t\t\tif err != nil { return err }\n")
			g.printf("\t\t\tm.%s = &v\n", fieldName)
		}
		g.printf("\t\t}\n")
		g.printf("\t}\n")
		return
	}

	// Handle repeated fields - V2: read count then elements
	if field.Repeated {
		elemMin := minWireBytes(field.Type, isEnum)
		g.printf("\t{\n")
		g.printf("\t\tvar count int32\n")
		g.printf("\t\tcount, pos, err = xpb.ReadArrayCountAt(data, pos, %d, %d)\n", elemMin, common.DefaultMaxElements)
		g.printf("\t\tif err != nil { return err }\n")
		g.printf("\t\tm.%s = make(%s, count)\n", fieldName, g.goTypeName(field))
		g.printf("\t\tfor i := int32(0); i < count; i++ {\n")
		if isEnum {
			g.printf("\t\t\tvar v int32\n")
			g.printf("\t\t\tv, pos, err = xpb.ReadInt32At(data, pos)\n")
			g.printf("\t\t\tif err != nil { return err }\n")
			g.printf("\t\t\tm.%s[i] = %s(v)\n", fieldName, field.Type.Message)
		} else {
			g.generateScalarDecodeInto(fmt.Sprintf("m.%s[i]", fieldName), field.Type, "\t\t\t", isEnum)
		}
		g.printf("\t\t}\n")
		g.printf("\t}\n")
		return
	}

	// Handle map fields - V2: read count then key-value pairs
	if field.Type.Kind == ast.TypeMap {
		keyMin := minWireBytes(*field.Type.KeyType, false)
		valMin := minWireBytes(*field.Type.ValType, g.isEnumType(*field.Type.ValType))
		g.printf("\t{\n")
		g.printf("\t\tvar count int32\n")
		g.printf("\t\tcount, pos, err = xpb.ReadArrayCountAt(data, pos, %d, %d)\n", keyMin+valMin, common.DefaultMaxElements)
		g.printf("\t\tif err != nil { return err }\n")
		g.printf("\t\tm.%s = make(%s)\n", fieldName, g.goTypeName(field))
		g.printf("\t\tfor i := int32(0); i < count; i++ {\n")
		g.printf("\t\t\tvar mk %s\n", g.goBaseTypeName(*field.Type.KeyType))
		g.printf("\t\t\tvar mv %s\n", g.goBaseTypeName(*field.Type.ValType))
		// Each decode is wrapped in its own block so the temporary `v`
		// declarations do not collide between key and value reads; pos/err
		// thread through the function-scoped cursor.
		g.printf("\t\t\t{\n")
		g.generateScalarDecodeInto("mk", *field.Type.KeyType, "\t\t\t\t", false)
		g.printf("\t\t\t}\n")
		g.printf("\t\t\t{\n")
		g.generateScalarDecodeInto("mv", *field.Type.ValType, "\t\t\t\t", g.isEnumType(*field.Type.ValType))
		g.printf("\t\t\t}\n")
		g.printf("\t\t\tm.%s[mk] = mv\n", fieldName)
		g.printf("\t\t}\n")
		g.printf("\t}\n")
		return
	}

	// Handle enum field
	if isEnum {
		g.printf("\t{\n")
		g.printf("\t\tvar v int32\n")
		g.printf("\t\tv, pos, err = xpb.ReadInt32At(data, pos)\n")
		g.printf("\t\tif err != nil { return err }\n")
		g.printf("\t\tm.%s = %s(v)\n", fieldName, field.Type.Message)
		g.printf("\t}\n")
		return
	}

	// Regular field - V2: no tags, just read in order
	g.printf("\t{\n")
	g.generateScalarDecodeInto("m."+fieldName, field.Type, "\t\t", isEnum)
	g.printf("\t}\n")
}

// runReadExpr returns the unchecked Run*At read expression for one fixed-width
// field at a known offset `off` within a coalesced run. It assumes the caller
// already verified the whole run is in-bounds via xpb.EnsureRunAt, so these
// readers carry no per-field bounds check. Enums read as int32 and are converted
// at the assignment site, so this returns the raw int32 reader for them.
func (g *Generator) runReadExpr(field *ast.Field, off int) string {
	if g.isEnumType(field.Type) {
		return fmt.Sprintf("xpb.RunInt32At(data, pos+%d)", off)
	}
	switch field.Type.Kind {
	case ast.TypeBool:
		return fmt.Sprintf("xpb.RunBoolAt(data, pos+%d)", off)
	case ast.TypeInt32:
		return fmt.Sprintf("xpb.RunInt32At(data, pos+%d)", off)
	case ast.TypeInt64:
		return fmt.Sprintf("xpb.RunInt64At(data, pos+%d)", off)
	case ast.TypeUint32:
		return fmt.Sprintf("xpb.RunUint32At(data, pos+%d)", off)
	case ast.TypeUint64:
		return fmt.Sprintf("xpb.RunUint64At(data, pos+%d)", off)
	case ast.TypeFloat32:
		return fmt.Sprintf("xpb.RunFloat32At(data, pos+%d)", off)
	case ast.TypeFloat64:
		return fmt.Sprintf("xpb.RunFloat64At(data, pos+%d)", off)
	}
	return ""
}

// generateRunDecode emits a coalesced decode for a maximal run of contiguous
// fixed-width fields. The whole run (runWidth bytes) is bounds-checked ONCE via
// xpb.EnsureRunAt; on success every field is read with an unchecked Run*At reader
// at its known offset from the run base, and the cursor advances by the run width
// exactly once. A truncated input that ends partway through the run fails the
// single EnsureRunAt with the same io.ErrUnexpectedEOF the per-field path would
// have produced — there is no per-field OOB to hit because the up-front check
// covers the entire window. The wire bytes consumed are identical to decoding the
// fields one at a time.
func (g *Generator) generateRunDecode(run []*ast.Field) {
	width := g.runWidth(run)
	g.printf("\t{\n")
	g.printf("\t\trunEnd, rerr := xpb.EnsureRunAt(data, pos, %d)\n", width)
	g.printf("\t\tif rerr != nil { return rerr }\n")
	off := 0
	for _, field := range run {
		fieldName := toCamelCase(field.Name)
		w, _ := g.fixedRunWidth(field)
		if g.isEnumType(field.Type) {
			// Enum (incl. enum-alias): read int32, convert to the enum type.
			g.printf("\t\tm.%s = %s(%s)\n", fieldName, field.Type.Message, g.runReadExpr(field, off))
		} else {
			g.printf("\t\tm.%s = %s\n", fieldName, g.runReadExpr(field, off))
		}
		off += w
	}
	g.printf("\t\tpos = runEnd\n")
	g.printf("\t}\n")
}

// runWriteStmt returns the Put*At write statement for one fixed-width field at a
// known offset `off` within a coalesced run, writing into the just-extended local
// buffer. Enums and enum aliases are written as int32. The destination region was
// extended once via xpb.ExtendRun, so these writers carry no per-field capacity
// check; every byte of the run is written exactly once.
func (g *Generator) runWriteStmt(field *ast.Field, valExpr string, off int) string {
	if g.isEnumType(field.Type) {
		return fmt.Sprintf("xpb.PutInt32At(buf, runOff+%d, int32(%s))", off, valExpr)
	}
	switch field.Type.Kind {
	case ast.TypeBool:
		return fmt.Sprintf("xpb.PutBoolAt(buf, runOff+%d, %s)", off, valExpr)
	case ast.TypeInt32:
		return fmt.Sprintf("xpb.PutInt32At(buf, runOff+%d, %s)", off, valExpr)
	case ast.TypeInt64:
		return fmt.Sprintf("xpb.PutInt64At(buf, runOff+%d, %s)", off, valExpr)
	case ast.TypeUint32:
		return fmt.Sprintf("xpb.PutUint32At(buf, runOff+%d, %s)", off, valExpr)
	case ast.TypeUint64:
		return fmt.Sprintf("xpb.PutUint64At(buf, runOff+%d, %s)", off, valExpr)
	case ast.TypeFloat32:
		return fmt.Sprintf("xpb.PutFloat32At(buf, runOff+%d, %s)", off, valExpr)
	case ast.TypeFloat64:
		return fmt.Sprintf("xpb.PutFloat64At(buf, runOff+%d, %s)", off, valExpr)
	}
	return ""
}

// generateRunEncode emits a coalesced encode for a maximal run of contiguous
// fixed-width fields. The local buffer is extended ONCE by the run width via
// xpb.ExtendRun (which returns the run's base offset), then each field is written
// at its known offset with an unchecked Put*At writer. This replaces the run's
// per-field Append*To capacity checks with a single grow. The bytes written are
// byte-identical to appending the fields one at a time.
func (g *Generator) generateRunEncode(run []*ast.Field) {
	width := g.runWidth(run)
	// Reassign the outer `buf` (not `:=`, which would shadow it inside the block
	// and discard the grown slice) so a reallocation in ExtendRun is visible to
	// the following fields and to enc.SetBuf(buf). runOff stays block-scoped so
	// successive runs do not collide.
	g.printf("\t{\n")
	g.printf("\t\tvar runOff int\n")
	g.printf("\t\tbuf, runOff = xpb.ExtendRun(buf, %d)\n", width)
	off := 0
	for _, field := range run {
		fieldName := toCamelCase(field.Name)
		w, _ := g.fixedRunWidth(field)
		g.printf("\t\t%s\n", g.runWriteStmt(field, "m."+fieldName, off))
		off += w
	}
	g.printf("\t}\n")
}

// scalarReadCall returns the stateless cursor read expression (which yields
// `(value, newPos, error)` and takes (data, pos)) for a scalar/string/bytes
// type. Used by the optional decode path, which reads into a fresh local
// before taking its address. Not valid for message/map/enum types.
func (g *Generator) scalarReadCall(t ast.FieldType) string {
	switch t.Kind {
	case ast.TypeBool:
		return "xpb.ReadBoolAt(data, pos)"
	case ast.TypeInt32:
		return "xpb.ReadInt32At(data, pos)"
	case ast.TypeInt64:
		return "xpb.ReadInt64At(data, pos)"
	case ast.TypeUint32:
		return "xpb.ReadUint32At(data, pos)"
	case ast.TypeUint64:
		return "xpb.ReadUint64At(data, pos)"
	case ast.TypeFloat32:
		return "xpb.ReadFloat32At(data, pos)"
	case ast.TypeFloat64:
		return "xpb.ReadFloat64At(data, pos)"
	case ast.TypeString:
		return "xpb.ReadStringAt(data, pos)"
	case ast.TypeBytes:
		return g.bytesReadCall()
	}
	return g.bytesReadCall()
}

// generateScalarDecodeInto emits a cursor-threaded read of a scalar/string/
// bytes/enum/message into varName. The cursor (pos) and err are the
// function-scoped variables, advanced with =; the decoded value goes through a
// fresh block-local `v` (each call site is wrapped in its own block, or is a
// fresh loop-body scope, so `v` never collides). The nested-message case reads
// the length-prefixed envelope via the cursor and recurses with depth+1.
func (g *Generator) generateScalarDecodeInto(varName string, t ast.FieldType, indent string, isEnum bool) {
	if isEnum {
		g.printf("%svar v int32\n", indent)
		g.printf("%sv, pos, err = xpb.ReadInt32At(data, pos)\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = %s(v)\n", indent, varName, t.Message)
		return
	}

	if t.Kind == ast.TypeMessage {
		// A nil/absent nested message encoded as a 0-length envelope must
		// decode back to a nil pointer rather than crashing. Skip the
		// allocation + recursive unmarshalAt when the length prefix is
		// empty — calling unmarshalAt on empty bytes errors at the
		// nested type's first ReadString/ReadBytes inside an empty
		// buffer. Leaves the destination nil, which is symmetric with
		// what a caller of the encode side would produce when the field
		// is nil. mb aliases the envelope body via the cursor read.
		g.printf("%svar mb []byte\n", indent)
		g.printf("%smb, pos, err = xpb.ReadMessageBytesAt(data, pos)\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%sif len(mb) > 0 {\n", indent)
		g.printf("%s\t%s = &%s{}\n", indent, varName, t.Message)
		g.printf("%s\tif err := %s.unmarshalAt(mb, depth+1); err != nil { return err }\n", indent, varName)
		g.printf("%s}\n", indent)
		return
	}

	g.printf("%svar v %s\n", indent, g.goBaseTypeName(t))
	g.printf("%sv, pos, err = %s\n", indent, g.scalarReadCall(t))
	g.printf("%sif err != nil { return err }\n", indent)
	g.printf("%s%s = v\n", indent, varName)
}

func (g *Generator) goTypeName(field *ast.Field) string {
	t := field.Type
	base := g.goBaseTypeName(t)

	if field.Repeated {
		return "[]" + base
	}
	if t.Kind == ast.TypeMap {
		return fmt.Sprintf("map[%s]%s", g.goBaseTypeName(*t.KeyType), g.goBaseTypeName(*t.ValType))
	}
	// Under the OptionalPointer opt-out, optional fields are pointers so
	// absence (nil) is distinguishable from a zero value. Message fields are
	// already pointers, so they stay as-is. Under the default OptionalValue
	// style, scalar/string/bytes/enum optionals are plain values paired with a
	// generated Has<Field> bool instead.
	if field.Optional && t.Kind != ast.TypeMessage && !g.valueOptional(field) {
		return "*" + base
	}
	return base
}

func (g *Generator) goBaseTypeName(t ast.FieldType) string {
	// Check if it's an enum
	if t.Kind == ast.TypeMessage && g.enums[t.Message] {
		return t.Message
	}

	switch t.Kind {
	case ast.TypeBool:
		return "bool"
	case ast.TypeInt32:
		return "int32"
	case ast.TypeInt64:
		return "int64"
	case ast.TypeUint32:
		return "uint32"
	case ast.TypeUint64:
		return "uint64"
	case ast.TypeFloat32:
		return "float32"
	case ast.TypeFloat64:
		return "float64"
	case ast.TypeString:
		return "string"
	case ast.TypeBytes:
		return "[]byte"
	case ast.TypeMessage:
		return "*" + t.Message
	case ast.TypeEnum:
		return t.Enum
	default:
		return "any"
	}
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func estimateSize(msg *ast.Message) int {
	size := 0
	for _, field := range msg.Fields {
		switch field.Type.Kind {
		case ast.TypeBool:
			size += wire.SizeBool
		case ast.TypeInt32, ast.TypeUint32, ast.TypeEnum:
			size += wire.SizeInt32
		case ast.TypeInt64, ast.TypeUint64:
			size += wire.SizeInt64
		case ast.TypeFloat32:
			size += wire.SizeFloat32
		case ast.TypeFloat64:
			size += wire.SizeFloat64
		case ast.TypeString, ast.TypeBytes:
			size += 32
		case ast.TypeMessage, ast.TypeMap:
			size += 64
		}
		if field.Repeated {
			size *= 4
		}
	}
	if size < 64 {
		return 64
	}
	return size
}

// fixedSizeLowerBound returns a safe lower bound on the encoded size of msg: the
// sum of the fixed-width wire sizes of every non-optional, non-repeated,
// non-map scalar/enum field, plus one presence byte for each optional field and
// a 4-byte count for each repeated/map field. Variable-length fields (string,
// bytes, nested message) contribute nothing, since their size is data-dependent.
// Growing the local encode buffer once by this amount up front replaces the
// per-field capacity checks of the append helpers for the fixed portion of the
// message, without ever over-allocating past what the message provably needs.
func (g *Generator) fixedSizeLowerBound(msg *ast.Message) int {
	size := 0
	for _, field := range msg.Fields {
		if field.Optional {
			// Optional fields always emit a 1-byte presence flag; the value
			// (if present) is data-dependent, so only the flag is counted.
			size += wire.SizeBool
			continue
		}
		if field.Repeated || field.Type.Kind == ast.TypeMap {
			// Repeated/map emit a 4-byte count then data-dependent elements;
			// the count alone is a safe fixed lower bound.
			size += wire.SizeInt32
			continue
		}
		// Enum-typed fields (whether Kind==TypeEnum or an enum alias coming
		// through Kind==TypeMessage) encode as a fixed 4-byte int32.
		if g.isEnumType(field.Type) {
			size += wire.SizeInt32
			continue
		}
		switch field.Type.Kind {
		case ast.TypeBool:
			size += wire.SizeBool
		case ast.TypeInt32, ast.TypeUint32:
			size += wire.SizeInt32
		case ast.TypeInt64, ast.TypeUint64:
			size += wire.SizeInt64
		case ast.TypeFloat32:
			size += wire.SizeFloat32
		case ast.TypeFloat64:
			size += wire.SizeFloat64
		case ast.TypeString, ast.TypeBytes, ast.TypeMessage:
			// Variable-length: a real nested message is at minimum a 1-byte
			// 0-length envelope, and string/bytes a 1-byte length, but those
			// are data-dependent past the prefix; count 0 to keep the bound safe.
		}
	}
	return size
}

// minCoalesceRun is the shortest run of contiguous fixed-width fields worth
// coalescing. A run of 1 already costs exactly one bounds check (decode) / one
// append's capacity check absorbed by the up-front GrowBuf (encode), so
// coalescing it would only obscure the generated code for no measurable gain.
const minCoalesceRun = 2

// fixedRunWidth reports the on-wire width of a field that may participate in a
// coalesced fixed-width run, and whether it qualifies at all. A field qualifies
// only when it is a single, unconditional, fixed-width value: non-optional,
// non-repeated, non-map, and a bool/int32/uint32/float32/enum (4) / int64/uint64/
// float64 (8) scalar. Anything optional (carries a presence byte then a
// conditional value), repeated/map (carries a count then a variable number of
// elements), or variable-length (string/bytes/nested message) breaks a run,
// because its byte span is data-dependent and cannot be bounds-checked or grown
// as part of a single contiguous region.
func (g *Generator) fixedRunWidth(field *ast.Field) (int, bool) {
	if field.Optional || field.Repeated || field.Type.Kind == ast.TypeMap {
		return 0, false
	}
	// Enums (whether Kind==TypeEnum or an enum alias arriving as TypeMessage)
	// encode as a fixed 4-byte int32.
	if g.isEnumType(field.Type) {
		return 4, true
	}
	switch field.Type.Kind {
	case ast.TypeBool:
		return 1, true
	case ast.TypeInt32, ast.TypeUint32, ast.TypeFloat32:
		return 4, true
	case ast.TypeInt64, ast.TypeUint64, ast.TypeFloat64:
		return 8, true
	default:
		// string, bytes, message: variable-length, breaks the run.
		return 0, false
	}
}

// fieldRuns partitions msg.Fields into consecutive groups. Each group is either
// a maximal run of coalescable fixed-width fields (length >= minCoalesceRun) or a
// trailing/standalone slice of fields handled one at a time. The returned slices
// reference msg.Fields in order, so concatenating every group reproduces the
// original field order exactly. `coalesced` reports, per group, whether the group
// is a fixed-width run to be emitted as a single bounds-checked / grown block.
func (g *Generator) fieldRuns(msg *ast.Message) (groups [][]*ast.Field, coalesced []bool) {
	i := 0
	for i < len(msg.Fields) {
		if _, ok := g.fixedRunWidth(msg.Fields[i]); ok {
			j := i + 1
			for j < len(msg.Fields) {
				if _, ok := g.fixedRunWidth(msg.Fields[j]); !ok {
					break
				}
				j++
			}
			if j-i >= minCoalesceRun {
				groups = append(groups, msg.Fields[i:j])
				coalesced = append(coalesced, true)
				i = j
				continue
			}
			// A run of length 1 (j-i == 1) falls through to the per-field path;
			// emit just that one field as a non-coalesced group of one.
		}
		groups = append(groups, msg.Fields[i:i+1])
		coalesced = append(coalesced, false)
		i++
	}
	return groups, coalesced
}

// runWidth sums the fixed wire widths of every field in a coalesced run.
func (g *Generator) runWidth(run []*ast.Field) int {
	total := 0
	for _, f := range run {
		w, _ := g.fixedRunWidth(f)
		total += w
	}
	return total
}

// minWireBytes returns the smallest possible on-wire size for one element of
// the given type. Used to bound the count of a repeated/map field against the
// remaining buffer in ReadArrayCount.
func minWireBytes(t ast.FieldType, isEnum bool) int {
	if isEnum {
		return 4
	}
	switch t.Kind {
	case ast.TypeBool:
		return 1
	case ast.TypeInt32, ast.TypeUint32, ast.TypeFloat32:
		return 4
	case ast.TypeInt64, ast.TypeUint64, ast.TypeFloat64:
		return 8
	case ast.TypeString, ast.TypeBytes, ast.TypeMessage:
		return 1
	}
	return 1
}
