// Package golang generates Go code from XPB schemas.
package golang

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/ElecTwix/xpb/pkg/ast"
	"github.com/ElecTwix/xpb/pkg/wire"
)

// Generator generates Go code from an AST.
type Generator struct {
	buf   bytes.Buffer
	enums map[string]bool // Track enum names for resolution
}

// Generate generates Go code for the given file AST.
func Generate(file *ast.File) ([]byte, error) {
	g := &Generator{
		enums: make(map[string]bool),
	}
	return g.generate(file)
}

func (g *Generator) generate(file *ast.File) ([]byte, error) {
	g.buf.Reset()

	// Build enum set for type resolution
	for _, enum := range file.Enums {
		g.enums[enum.Name] = true
	}

	pkg := file.Package
	if pkg == "" {
		pkg = "main"
	}
	g.printf("// Code generated by xpbc. DO NOT EDIT.\n")
	g.printf("package %s\n\n", pkg)

	g.printf("import (\n")
	g.printf("\t\"github.com/ElecTwix/xpb/runtime/go/xpb\"\n")
	g.printf(")\n\n")

	g.printf("var _ = xpb.NewEncoder\n\n")

	// Generate enums
	for _, enum := range file.Enums {
		g.generateEnum(enum)
	}

	// Generate messages
	for _, msg := range file.Messages {
		if err := g.generateMessage(msg); err != nil {
			return nil, err
		}
	}

	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		return g.buf.Bytes(), fmt.Errorf("format error: %w", err)
	}
	return src, nil
}

func (g *Generator) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) generateEnum(enum *ast.Enum) {
	name := enum.Name
	g.printf("// %s is an enum type.\n", name)
	g.printf("type %s int32\n\n", name)
	g.printf("const (\n")
	for _, v := range enum.Values {
		g.printf("\t%s_%s %s = %d\n", name, v.Name, name, v.Number)
	}
	g.printf(")\n\n")

	g.printf("func (e %s) String() string {\n", name)
	g.printf("\tswitch e {\n")
	for _, v := range enum.Values {
		g.printf("\tcase %s_%s:\n", name, v.Name)
		g.printf("\t\treturn \"%s\"\n", v.Name)
	}
	g.printf("\tdefault:\n")
	g.printf("\t\treturn \"UNKNOWN\"\n")
	g.printf("\t}\n")
	g.printf("}\n\n")
}

func (g *Generator) generateMessage(msg *ast.Message) error {
	name := msg.Name

	// Struct
	g.printf("// %s is a generated XPB message.\n", name)
	g.printf("type %s struct {\n", name)
	for _, field := range msg.Fields {
		goType := g.goTypeName(field)
		g.printf("\t%s %s\n", toCamelCase(field.Name), goType)
	}
	g.printf("}\n\n")

	// Marshal - V2: no tags, fields in order
	g.printf("func (m *%s) Marshal() ([]byte, error) {\n", name)
	g.printf("\tenc := xpb.NewEncoder(%d)\n", estimateSize(msg))
	for _, field := range msg.Fields {
		g.generateFieldEncode(field)
	}
	g.printf("\treturn enc.Bytes(), nil\n")
	g.printf("}\n\n")

	// MarshalTo
	g.printf("func (m *%s) MarshalTo(enc *xpb.Encoder) {\n", name)
	for _, field := range msg.Fields {
		g.generateFieldEncode(field)
	}
	g.printf("}\n\n")

	// Unmarshal - V2: no tags, read fields in order
	g.printf("func (m *%s) Unmarshal(data []byte) error {\n", name)
	g.printf("\treturn m.unmarshalAt(data, 0)\n")
	g.printf("}\n\n")

	g.printf("func (m *%s) unmarshalAt(data []byte, depth int) error {\n", name)
	g.printf("\tif depth > xpb.MaxDecodeDepth { return xpb.ErrMaxDepthExceeded }\n")
	g.printf("\tdec := xpb.NewDecoder(data)\n")
	for _, field := range msg.Fields {
		g.generateFieldDecode(field)
	}
	g.printf("\treturn nil\n")
	g.printf("}\n\n")

	return nil
}

// isEnumType checks if the type name refers to an enum
func (g *Generator) isEnumType(t ast.FieldType) bool {
	if t.Kind == ast.TypeMessage && g.enums[t.Message] {
		return true
	}
	return t.Kind == ast.TypeEnum
}

func (g *Generator) generateFieldEncode(field *ast.Field) {
	fieldName := toCamelCase(field.Name)
	isEnum := g.isEnumType(field.Type)

	// Handle repeated fields - V2: write count then elements
	if field.Repeated {
		g.printf("\tenc.WriteInt32(int32(len(m.%s)))\n", fieldName)
		g.printf("\tfor _, v := range m.%s {\n", fieldName)
		g.generateScalarEncode("v", field.Type, "\t\t", isEnum)
		g.printf("\t}\n")
		return
	}

	// Handle map fields - V2: write count then key-value pairs
	if field.Type.Kind == ast.TypeMap {
		g.printf("\tenc.WriteInt32(int32(len(m.%s)))\n", fieldName)
		g.printf("\tfor k, v := range m.%s {\n", fieldName)
		g.generateScalarEncode("k", *field.Type.KeyType, "\t\t", false)
		g.generateScalarEncode("v", *field.Type.ValType, "\t\t", g.isEnumType(*field.Type.ValType))
		g.printf("\t}\n")
		return
	}

	// Regular field - V2: no tags
	g.generateScalarEncode("m."+fieldName, field.Type, "\t", isEnum)
}

func (g *Generator) generateScalarEncode(varName string, t ast.FieldType, indent string, isEnum bool) {
	if isEnum || t.Kind == ast.TypeEnum {
		g.printf("%senc.WriteInt32(int32(%s))\n", indent, varName)
		return
	}

	switch t.Kind {
	case ast.TypeBool:
		g.printf("%senc.WriteBool(%s)\n", indent, varName)
	case ast.TypeInt32:
		g.printf("%senc.WriteInt32(%s)\n", indent, varName)
	case ast.TypeInt64:
		g.printf("%senc.WriteInt64(%s)\n", indent, varName)
	case ast.TypeUint32:
		g.printf("%senc.WriteUint32(%s)\n", indent, varName)
	case ast.TypeUint64:
		g.printf("%senc.WriteUint64(%s)\n", indent, varName)
	case ast.TypeFloat32:
		g.printf("%senc.WriteFloat32(%s)\n", indent, varName)
	case ast.TypeFloat64:
		g.printf("%senc.WriteFloat64(%s)\n", indent, varName)
	case ast.TypeString:
		g.printf("%senc.WriteString(%s)\n", indent, varName)
	case ast.TypeBytes:
		g.printf("%senc.WriteBytes(%s)\n", indent, varName)
	case ast.TypeMessage:
		g.printf("%s{\n", indent)
		g.printf("%s\tnestedEnc := xpb.GetEncoder()\n", indent)
		g.printf("%s\t%s.MarshalTo(nestedEnc)\n", indent, varName)
		g.printf("%s\tenc.WriteMessage(nestedEnc.Bytes())\n", indent)
		g.printf("%s\txpb.PutEncoder(nestedEnc)\n", indent)
		g.printf("%s}\n", indent)
	}
}

func (g *Generator) generateFieldDecode(field *ast.Field) {
	fieldName := toCamelCase(field.Name)
	isEnum := g.isEnumType(field.Type)

	// Handle repeated fields - V2: read count then elements
	if field.Repeated {
		elemMin := minWireBytes(field.Type, isEnum)
		g.printf("\t{\n")
		g.printf("\t\tcount, err := dec.ReadArrayCount(%d)\n", elemMin)
		g.printf("\t\tif err != nil { return err }\n")
		g.printf("\t\tm.%s = make(%s, count)\n", fieldName, g.goTypeName(field))
		g.printf("\t\tfor i := int32(0); i < count; i++ {\n")
		if isEnum {
			g.printf("\t\t\tv, err := dec.ReadInt32()\n")
			g.printf("\t\t\tif err != nil { return err }\n")
			g.printf("\t\t\tm.%s[i] = %s(v)\n", fieldName, field.Type.Message)
		} else {
			g.generateScalarDecodeInto(fmt.Sprintf("m.%s[i]", fieldName), field.Type, "\t\t\t", isEnum)
		}
		g.printf("\t\t}\n")
		g.printf("\t}\n")
		return
	}

	// Handle map fields - V2: read count then key-value pairs
	if field.Type.Kind == ast.TypeMap {
		keyMin := minWireBytes(*field.Type.KeyType, false)
		valMin := minWireBytes(*field.Type.ValType, g.isEnumType(*field.Type.ValType))
		g.printf("\t{\n")
		g.printf("\t\tcount, err := dec.ReadArrayCount(%d)\n", keyMin+valMin)
		g.printf("\t\tif err != nil { return err }\n")
		g.printf("\t\tm.%s = make(%s)\n", fieldName, g.goTypeName(field))
		g.printf("\t\tfor i := int32(0); i < count; i++ {\n")
		g.printf("\t\t\tvar mk %s\n", g.goBaseTypeName(*field.Type.KeyType))
		g.printf("\t\t\tvar mv %s\n", g.goBaseTypeName(*field.Type.ValType))
		g.generateScalarDecodeInto("mk", *field.Type.KeyType, "\t\t\t", false)
		g.generateScalarDecodeInto("mv", *field.Type.ValType, "\t\t\t", g.isEnumType(*field.Type.ValType))
		g.printf("\t\t\tm.%s[mk] = mv\n", fieldName)
		g.printf("\t\t}\n")
		g.printf("\t}\n")
		return
	}

	// Handle enum field
	if isEnum {
		g.printf("\t{\n")
		g.printf("\t\tv, err := dec.ReadInt32()\n")
		g.printf("\t\tif err != nil { return err }\n")
		g.printf("\t\tm.%s = %s(v)\n", fieldName, field.Type.Message)
		g.printf("\t}\n")
		return
	}

	// Regular field - V2: no tags, just read in order
	g.printf("\t{\n")
	g.generateScalarDecodeInto("m."+fieldName, field.Type, "\t\t", isEnum)
	g.printf("\t}\n")
}

func (g *Generator) generateScalarDecodeInto(varName string, t ast.FieldType, indent string, isEnum bool) {
	if isEnum {
		g.printf("%sv, err := dec.ReadInt32()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = %s(v)\n", indent, varName, t.Message)
		return
	}

	switch t.Kind {
	case ast.TypeBool:
		g.printf("%sv, err := dec.ReadBool()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = v\n", indent, varName)
	case ast.TypeInt32:
		g.printf("%sv, err := dec.ReadInt32()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = v\n", indent, varName)
	case ast.TypeInt64:
		g.printf("%sv, err := dec.ReadInt64()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = v\n", indent, varName)
	case ast.TypeUint32:
		g.printf("%sv, err := dec.ReadUint32()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = v\n", indent, varName)
	case ast.TypeUint64:
		g.printf("%sv, err := dec.ReadUint64()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = v\n", indent, varName)
	case ast.TypeFloat32:
		g.printf("%sv, err := dec.ReadFloat32()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = v\n", indent, varName)
	case ast.TypeFloat64:
		g.printf("%sv, err := dec.ReadFloat64()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = v\n", indent, varName)
	case ast.TypeString:
		g.printf("%sv, err := dec.ReadString()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = v\n", indent, varName)
	case ast.TypeBytes:
		g.printf("%sv, err := dec.ReadBytes()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = v\n", indent, varName)
	case ast.TypeMessage:
		g.printf("%sdata, err := dec.ReadMessageBytes()\n", indent)
		g.printf("%sif err != nil { return err }\n", indent)
		g.printf("%s%s = &%s{}\n", indent, varName, t.Message)
		g.printf("%sif err := %s.unmarshalAt(data, depth+1); err != nil { return err }\n", indent, varName)
	}
}

func (g *Generator) goTypeName(field *ast.Field) string {
	t := field.Type
	base := g.goBaseTypeName(t)

	if field.Repeated {
		return "[]" + base
	}
	if t.Kind == ast.TypeMap {
		return fmt.Sprintf("map[%s]%s", g.goBaseTypeName(*t.KeyType), g.goBaseTypeName(*t.ValType))
	}
	return base
}

func (g *Generator) goBaseTypeName(t ast.FieldType) string {
	// Check if it's an enum
	if t.Kind == ast.TypeMessage && g.enums[t.Message] {
		return t.Message
	}

	switch t.Kind {
	case ast.TypeBool:
		return "bool"
	case ast.TypeInt32:
		return "int32"
	case ast.TypeInt64:
		return "int64"
	case ast.TypeUint32:
		return "uint32"
	case ast.TypeUint64:
		return "uint64"
	case ast.TypeFloat32:
		return "float32"
	case ast.TypeFloat64:
		return "float64"
	case ast.TypeString:
		return "string"
	case ast.TypeBytes:
		return "[]byte"
	case ast.TypeMessage:
		return "*" + t.Message
	case ast.TypeEnum:
		return t.Enum
	default:
		return "any"
	}
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func estimateSize(msg *ast.Message) int {
	size := 0
	for _, field := range msg.Fields {
		switch field.Type.Kind {
		case ast.TypeBool:
			size += wire.SizeBool
		case ast.TypeInt32, ast.TypeUint32, ast.TypeEnum:
			size += wire.SizeInt32
		case ast.TypeInt64, ast.TypeUint64:
			size += wire.SizeInt64
		case ast.TypeFloat32:
			size += wire.SizeFloat32
		case ast.TypeFloat64:
			size += wire.SizeFloat64
		case ast.TypeString, ast.TypeBytes:
			size += 32
		case ast.TypeMessage, ast.TypeMap:
			size += 64
		}
		if field.Repeated {
			size *= 4
		}
	}
	if size < 64 {
		return 64
	}
	return size
}

// minWireBytes returns the smallest possible on-wire size for one element of
// the given type. Used to bound the count of a repeated/map field against the
// remaining buffer in ReadArrayCount.
func minWireBytes(t ast.FieldType, isEnum bool) int {
	if isEnum {
		return 4
	}
	switch t.Kind {
	case ast.TypeBool:
		return 1
	case ast.TypeInt32, ast.TypeUint32, ast.TypeFloat32:
		return 4
	case ast.TypeInt64, ast.TypeUint64, ast.TypeFloat64:
		return 8
	case ast.TypeString, ast.TypeBytes, ast.TypeMessage:
		return 1
	}
	return 1
}
