// Package rust generates Rust code from XPB schemas.
package rust

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/ElecTwix/xpb/pkg/ast"
	"github.com/ElecTwix/xpb/pkg/codegen/common"
)

// Generate generates Rust code for the given file AST.
func Generate(file *ast.File) ([]byte, error) {
	g := &generator{enums: ast.NewEnumSet(file)}
	return g.generate(file)
}

type generator struct {
	buf   bytes.Buffer
	enums ast.EnumSet
}

func (g *generator) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *generator) generate(file *ast.File) ([]byte, error) {
	g.printf("// Code generated by xpbc. DO NOT EDIT.\n\n")
	g.printf("use xpb::{Encoder, Decoder, Result, XpbError, MAX_DECODE_DEPTH};\n")

	needsHashMap := false
	for _, m := range file.Messages {
		for _, f := range m.Fields {
			if f.Type.Kind == ast.TypeMap {
				needsHashMap = true
				break
			}
		}
		if needsHashMap {
			break
		}
	}
	if needsHashMap {
		g.printf("use std::collections::HashMap;\n")
	}
	g.printf("\n")

	for _, e := range file.Enums {
		g.generateEnum(e)
	}
	for _, m := range file.Messages {
		g.generateMessage(m)
	}

	return g.buf.Bytes(), nil
}

func (g *generator) generateEnum(e *ast.Enum) {
	g.printf("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n")
	g.printf("#[repr(i32)]\n")
	g.printf("pub enum %s {\n", e.Name)
	for _, v := range e.Values {
		g.printf("    %s = %d,\n", v.Name, v.Number)
	}
	g.printf("}\n\n")

	g.printf("impl %s {\n", e.Name)
	g.printf("    pub fn from_i32(v: i32) -> Self {\n")
	g.printf("        match v {\n")
	for _, v := range e.Values {
		g.printf("            %d => %s::%s,\n", v.Number, e.Name, v.Name)
	}
	g.printf("            _ => %s::%s,\n", e.Name, e.Values[0].Name)
	g.printf("        }\n")
	g.printf("    }\n")
	g.printf("}\n\n")

	// Default impl for enums (returns first value)
	g.printf("impl Default for %s {\n", e.Name)
	g.printf("    fn default() -> Self {\n")
	g.printf("        %s::%s\n", e.Name, e.Values[0].Name)
	g.printf("    }\n")
	g.printf("}\n\n")
}

func (g *generator) generateMessage(m *ast.Message) {
	hasOptional := false
	for _, f := range m.Fields {
		if f.Optional {
			hasOptional = true
			break
		}
	}
	if hasOptional {
		g.printf("// NOTE: schema contains `optional` fields. The XPB V2 wire format has no\n")
		g.printf("// presence bit, so this codegen emits them as required on the wire.\n")
		g.printf("// Callers must agree on a sentinel value (or upgrade to V3) before\n")
		g.printf("// relying on optional semantics.\n")
	}

	g.printf("#[derive(Debug, Clone, Default)]\n")
	g.printf("pub struct %s {\n", m.Name)
	for _, f := range m.Fields {
		rustType := g.rustType(f)
		g.printf("    pub %s: %s,\n", toSnakeCase(f.Name), rustType)
	}
	g.printf("}\n\n")

	g.printf("impl %s {\n", m.Name)
	g.printf("    pub fn marshal(&self) -> Vec<u8> {\n")
	g.printf("        let mut enc = Encoder::new(64);\n")
	g.printf("        self.marshal_to(&mut enc);\n")
	g.printf("        enc.finish()\n")
	g.printf("    }\n\n")

	g.printf("    pub fn marshal_to(&self, enc: &mut Encoder) {\n")
	for _, f := range m.Fields {
		g.generateFieldEncode(f)
	}
	g.printf("    }\n\n")

	// Public entry point delegates to the depth-threaded helper. Without
	// this cap, a hand-crafted recursive payload blows the Rust thread
	// stack (default 8 MiB on Linux, 512 KiB on some embedded targets).
	g.printf("    pub fn unmarshal(data: &[u8]) -> Result<Self> {\n")
	g.printf("        let mut dec = Decoder::new(data);\n")
	g.printf("        Self::unmarshal_at(&mut dec, 0)\n")
	g.printf("    }\n\n")

	g.printf("    pub fn unmarshal_from(dec: &mut Decoder) -> Result<Self> {\n")
	g.printf("        Self::unmarshal_at(dec, 0)\n")
	g.printf("    }\n\n")

	g.printf("    pub fn unmarshal_at(dec: &mut Decoder, depth: u32) -> Result<Self> {\n")
	g.printf("        if depth > MAX_DECODE_DEPTH {\n")
	g.printf("            return Err(XpbError::InvalidData(\"xpb: max decode depth exceeded\".into()));\n")
	g.printf("        }\n")
	g.printf("        let mut msg = Self::default();\n")
	for _, f := range m.Fields {
		g.generateFieldDecode(f)
	}
	g.printf("        Ok(msg)\n")
	g.printf("    }\n")
	g.printf("}\n\n")
}

func (g *generator) generateFieldEncode(f *ast.Field) {
	name := "self." + toSnakeCase(f.Name)
	isEnum := g.enums[f.Type.Enum] || g.enums[f.Type.Message]

	if f.Optional {
		g.printf("        enc.write_bool(%s.is_some());\n", name)
		g.printf("        if let Some(ref v) = %s {\n", name)
		g.generateScalarEncode("v", f.Type, "            ", isEnum, true)
		g.printf("        }\n")
		return
	}

	if f.Repeated {
		g.printf("        enc.write_int32(%s.len() as i32);\n", name)
		g.printf("        for v in &%s {\n", name)
		g.generateScalarEncode("v", f.Type, "            ", isEnum, true)
		g.printf("        }\n")
		return
	}

	if f.Type.Kind == ast.TypeMap {
		g.printf("        enc.write_int32(%s.len() as i32);\n", name)
		g.printf("        for (k, v) in &%s {\n", name)
		g.generateScalarEncode("k", *f.Type.KeyType, "            ", false, true)
		g.generateScalarEncode("v", *f.Type.ValType, "            ", g.enums[f.Type.ValType.Message], true)
		g.printf("        }\n")
		return
	}

	g.generateScalarEncode(name, f.Type, "        ", isEnum, false)
}

func (g *generator) generateScalarEncode(varName string, ft ast.FieldType, indent string, isEnum bool, isRef bool) {
	deref := ""
	if isRef {
		deref = "*"
	}
	switch ft.Kind {
	case ast.TypeBool:
		g.printf("%senc.write_bool(%s%s);\n", indent, deref, varName)
	case ast.TypeInt32:
		g.printf("%senc.write_int32(%s%s);\n", indent, deref, varName)
	case ast.TypeInt64:
		g.printf("%senc.write_int64(%s%s);\n", indent, deref, varName)
	case ast.TypeUint32:
		g.printf("%senc.write_uint32(%s%s);\n", indent, deref, varName)
	case ast.TypeUint64:
		g.printf("%senc.write_uint64(%s%s);\n", indent, deref, varName)
	case ast.TypeFloat32:
		g.printf("%senc.write_float32(%s%s);\n", indent, deref, varName)
	case ast.TypeFloat64:
		g.printf("%senc.write_float64(%s%s);\n", indent, deref, varName)
	case ast.TypeString:
		g.printf("%senc.write_string(%s%s);\n", indent, refPrefix(isRef), varName)
	case ast.TypeBytes:
		g.printf("%senc.write_bytes(&%s);\n", indent, varName)
	case ast.TypeEnum:
		g.printf("%senc.write_int32(%s%s as i32);\n", indent, deref, varName)
	case ast.TypeMessage:
		if isEnum {
			g.printf("%senc.write_int32(%s%s as i32);\n", indent, deref, varName)
		} else {
			g.printf("%s%s.marshal_to(enc);\n", indent, varName)
		}
	}
}

func (g *generator) generateFieldDecode(f *ast.Field) {
	name := "msg." + toSnakeCase(f.Name)
	isEnum := g.enums.IsEnum(f.Type)

	if f.Optional {
		g.printf("        if dec.read_bool()? {\n")
		g.printf("            %s = Some(%s);\n", name, g.generateScalarDecode(f.Type, isEnum))
		g.printf("        }\n")
		return
	}

	if f.Repeated {
		min := g.rustMinWireBytes(f.Type, isEnum)
		g.printf("        {\n")
		g.printf("            let count = dec.read_array_count(%d, %d)?;\n", min, common.DefaultMaxElements)
		g.printf("            %s = Vec::with_capacity(count);\n", name)
		g.printf("            for _ in 0..count {\n")
		if f.Type.Kind == ast.TypeMessage && !isEnum {
			g.printf("                %s.push(%s::unmarshal_at(dec, depth + 1)?);\n", name, f.Type.Message)
		} else {
			g.printf("                %s.push(%s);\n", name, g.generateScalarDecode(f.Type, isEnum))
		}
		g.printf("            }\n")
		g.printf("        }\n")
		return
	}

	if f.Type.Kind == ast.TypeMap {
		keyMin := g.rustMinWireBytes(*f.Type.KeyType, false)
		valMin := g.rustMinWireBytes(*f.Type.ValType, g.enums.IsEnum(*f.Type.ValType))
		g.printf("        {\n")
		g.printf("            let count = dec.read_array_count(%d, %d)?;\n", keyMin+valMin, common.DefaultMaxElements)
		g.printf("            for _ in 0..count {\n")
		g.printf("                let k = %s;\n", g.generateScalarDecode(*f.Type.KeyType, false))
		g.printf("                let v = %s;\n", g.generateScalarDecode(*f.Type.ValType, g.enums.IsEnum(*f.Type.ValType)))
		g.printf("                %s.insert(k, v);\n", name)
		g.printf("            }\n")
		g.printf("        }\n")
		return
	}

	// Plain message field gets the depth-threaded helper; everything else
	// goes through the scalar decode.
	if f.Type.Kind == ast.TypeMessage && !isEnum {
		g.printf("        %s = %s::unmarshal_at(dec, depth + 1)?;\n", name, f.Type.Message)
		return
	}

	g.printf("        %s = %s;\n", name, g.generateScalarDecode(f.Type, isEnum))
}

// rustMinWireBytes mirrors the per-language helpers in c/java/lua/typescript:
// the smallest possible on-wire size of one element of `t`. The runtime's
// read_array_count uses this to bound a wire-supplied count against the
// remaining buffer.
func (g *generator) rustMinWireBytes(t ast.FieldType, isEnum bool) int {
	if isEnum {
		return 4
	}
	switch t.Kind {
	case ast.TypeBool:
		return 1
	case ast.TypeInt32, ast.TypeUint32, ast.TypeFloat32:
		return 4
	case ast.TypeInt64, ast.TypeUint64, ast.TypeFloat64:
		return 8
	case ast.TypeString, ast.TypeBytes, ast.TypeMessage:
		return 1
	}
	return 1
}

func (g *generator) generateScalarDecode(ft ast.FieldType, isEnum bool) string {
	switch ft.Kind {
	case ast.TypeBool:
		return "dec.read_bool()?"
	case ast.TypeInt32:
		return "dec.read_int32()?"
	case ast.TypeInt64:
		return "dec.read_int64()?"
	case ast.TypeUint32:
		return "dec.read_uint32()?"
	case ast.TypeUint64:
		return "dec.read_uint64()?"
	case ast.TypeFloat32:
		return "dec.read_float32()?"
	case ast.TypeFloat64:
		return "dec.read_float64()?"
	case ast.TypeString:
		return "dec.read_string()?"
	case ast.TypeBytes:
		return "dec.read_bytes()?"
	case ast.TypeEnum:
		return fmt.Sprintf("%s::from_i32(dec.read_int32()?)", ft.Enum)
	case ast.TypeMessage:
		if isEnum {
			return fmt.Sprintf("%s::from_i32(dec.read_int32()?)", ft.Message)
		}
		// Plain message in a generic position (e.g. as a map value).
		// Pass depth=0 because we don't have access to the surrounding
		// `depth` here; the recursive case is handled at the field-decode
		// level which threads depth+1 directly. This branch is reached
		// only via the scalar helpers, where the legacy unmarshal_from
		// shim still applies.
		return fmt.Sprintf("%s::unmarshal_from(dec)?", ft.Message)
	default:
		return "dec.read_bytes()?"
	}
}

func (g *generator) rustType(f *ast.Field) string {
	base := g.rustBaseType(f.Type)
	if f.Repeated {
		return fmt.Sprintf("Vec<%s>", base)
	}
	if f.Optional {
		return fmt.Sprintf("Option<%s>", base)
	}
	if f.Type.Kind == ast.TypeMap {
		keyType := g.rustBaseType(*f.Type.KeyType)
		valType := g.rustBaseType(*f.Type.ValType)
		return fmt.Sprintf("HashMap<%s, %s>", keyType, valType)
	}
	return base
}

func (g *generator) rustBaseType(ft ast.FieldType) string {
	switch ft.Kind {
	case ast.TypeBool:
		return "bool"
	case ast.TypeInt32:
		return "i32"
	case ast.TypeInt64:
		return "i64"
	case ast.TypeUint32:
		return "u32"
	case ast.TypeUint64:
		return "u64"
	case ast.TypeFloat32:
		return "f32"
	case ast.TypeFloat64:
		return "f64"
	case ast.TypeString:
		return "String"
	case ast.TypeBytes:
		return "Vec<u8>"
	case ast.TypeEnum:
		return ft.Enum
	case ast.TypeMessage:
		return ft.Message
	default:
		return "Vec<u8>"
	}
}

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32) // toLower
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

func refPrefix(isRef bool) string {
	if isRef {
		return ""
	}
	return "&"
}
