//! Timed cross-runtime benchmark harness for the Rust runtime (xpbench / T-17).
//!
//! This is the Rust arm of the cross-runtime benchmark TABLE driven by
//! `cmd/xpbench`. It is the timed analogue of the proven differential runner
//! (`runtime/rust/examples/diff_runner.rs`): it reads the shared `vectors.json`
//! manifest + `.bin` corpus the Go reference encoder wrote, then for every
//! vector times an encode loop (re-encode the ops with the Rust `Encoder`) and a
//! decode loop (decode + verify the `.bin` bytes with the Rust `Decoder`) over a
//! per-vector iteration count, and prints a JSON array of
//! `{name, encodeNs, decodeNs, wireSize}` to stdout for the Go driver to
//! normalize into table rows.
//!
//! Usage:  xpbench_rust <corpus-dir>
//!
//! Unlike the differential runner it hand-rolls a tiny JSON parser instead of
//! pulling in `serde_json`, so the throwaway cargo project the Go driver builds
//! needs nothing on the dependency line beyond the repo's `xpb` crate (no
//! registry/network access).

use std::fs;
use std::hint::black_box;
use std::path::PathBuf;
use std::process::exit;
use std::time::Instant;

use xpb::{Decoder, Encoder};

// ---------------------------------------------------------------------------
// Minimal JSON value model + recursive-descent parser (objects, arrays,
// strings, numbers, bool, null). Self-contained; handles the escapes/UTF-8 the
// manifest uses. Deliberately permissive: the manifest is machine-generated by
// the Go corpus writer, so this never has to defend against adversarial input.
// ---------------------------------------------------------------------------

enum Json {
    Null,
    Bool(bool),
    Num(f64),
    Str(String),
    Arr(Vec<Json>),
    Obj(Vec<(String, Json)>),
}

impl Json {
    fn get(&self, key: &str) -> Option<&Json> {
        if let Json::Obj(members) = self {
            for (k, v) in members {
                if k == key {
                    return Some(v);
                }
            }
        }
        None
    }
    fn as_str(&self) -> Option<&str> {
        if let Json::Str(s) = self {
            Some(s)
        } else {
            None
        }
    }
    fn as_f64(&self) -> Option<f64> {
        if let Json::Num(n) = self {
            Some(*n)
        } else {
            None
        }
    }
    fn as_bool(&self) -> Option<bool> {
        if let Json::Bool(b) = self {
            Some(*b)
        } else {
            None
        }
    }
    fn as_array(&self) -> &[Json] {
        if let Json::Arr(a) = self {
            a
        } else {
            &[]
        }
    }
}

struct Parser<'a> {
    b: &'a [u8],
    pos: usize,
}

impl<'a> Parser<'a> {
    fn new(s: &'a str) -> Self {
        Parser { b: s.as_bytes(), pos: 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.b.len() {
            match self.b[self.pos] {
                b' ' | b'\t' | b'\n' | b'\r' => self.pos += 1,
                _ => break,
            }
        }
    }

    fn value(&mut self) -> Json {
        self.skip_ws();
        match self.b.get(self.pos).copied().unwrap_or(b'n') {
            b'{' => self.object(),
            b'[' => self.array(),
            b'"' => Json::Str(self.string()),
            b't' => {
                self.pos += 4;
                Json::Bool(true)
            }
            b'f' => {
                self.pos += 5;
                Json::Bool(false)
            }
            b'n' => {
                self.pos += 4;
                Json::Null
            }
            _ => self.number(),
        }
    }

    fn object(&mut self) -> Json {
        self.pos += 1; // {
        let mut members = Vec::new();
        self.skip_ws();
        if self.b.get(self.pos) == Some(&b'}') {
            self.pos += 1;
            return Json::Obj(members);
        }
        loop {
            self.skip_ws();
            let key = self.string();
            self.skip_ws();
            self.pos += 1; // :
            let val = self.value();
            members.push((key, val));
            self.skip_ws();
            let c = self.b.get(self.pos).copied().unwrap_or(b'}');
            self.pos += 1;
            if c == b'}' {
                break;
            }
        }
        Json::Obj(members)
    }

    fn array(&mut self) -> Json {
        self.pos += 1; // [
        let mut items = Vec::new();
        self.skip_ws();
        if self.b.get(self.pos) == Some(&b']') {
            self.pos += 1;
            return Json::Arr(items);
        }
        loop {
            self.skip_ws();
            items.push(self.value());
            self.skip_ws();
            let c = self.b.get(self.pos).copied().unwrap_or(b']');
            self.pos += 1;
            if c == b']' {
                break;
            }
        }
        Json::Arr(items)
    }

    fn string(&mut self) -> String {
        self.pos += 1; // opening quote
        let mut out: Vec<u8> = Vec::new();
        while self.pos < self.b.len() {
            let c = self.b[self.pos];
            self.pos += 1;
            if c == b'"' {
                return String::from_utf8(out).unwrap_or_default();
            } else if c == b'\\' {
                let e = self.b[self.pos];
                self.pos += 1;
                match e {
                    b'"' => out.push(b'"'),
                    b'\\' => out.push(b'\\'),
                    b'/' => out.push(b'/'),
                    b'b' => out.push(0x08),
                    b'f' => out.push(0x0C),
                    b'n' => out.push(b'\n'),
                    b'r' => out.push(b'\r'),
                    b't' => out.push(b'\t'),
                    b'u' => {
                        let mut cp = self.hex4();
                        if (0xD800..=0xDBFF).contains(&cp) {
                            self.pos += 2; // consume the "\u" of the low surrogate
                            let lo = self.hex4();
                            cp = 0x10000 + ((cp - 0xD800) << 10) + (lo - 0xDC00);
                        }
                        let ch = char::from_u32(cp).unwrap_or('\u{FFFD}');
                        let mut buf = [0u8; 4];
                        out.extend_from_slice(ch.encode_utf8(&mut buf).as_bytes());
                    }
                    _ => {}
                }
            } else {
                out.push(c);
            }
        }
        String::from_utf8(out).unwrap_or_default()
    }

    fn hex4(&mut self) -> u32 {
        let mut v = 0u32;
        for _ in 0..4 {
            let c = self.b.get(self.pos).copied().unwrap_or(b'0');
            self.pos += 1;
            let d = match c {
                b'0'..=b'9' => (c - b'0') as u32,
                b'a'..=b'f' => (c - b'a' + 10) as u32,
                b'A'..=b'F' => (c - b'A' + 10) as u32,
                _ => 0,
            };
            v = (v << 4) | d;
        }
        v
    }

    fn number(&mut self) -> Json {
        let start = self.pos;
        while self.pos < self.b.len() {
            match self.b[self.pos] {
                b'0'..=b'9' | b'-' | b'+' | b'.' | b'e' | b'E' => self.pos += 1,
                _ => break,
            }
        }
        let s = std::str::from_utf8(&self.b[start..self.pos]).unwrap_or("0");
        Json::Num(s.parse().unwrap_or(0.0))
    }
}

// ---------------------------------------------------------------------------
// hex + bit-pattern helpers (mirror the differential runner).
// ---------------------------------------------------------------------------

fn strip_hex_prefix(s: &str) -> &str {
    s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")).unwrap_or(s)
}

fn hex_decode(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .filter_map(|i| u8::from_str_radix(s.get(i..i + 2)?, 16).ok())
        .collect()
}

// ---------------------------------------------------------------------------
// Encode + decode/verify ops (the timed work).
// ---------------------------------------------------------------------------

fn encode_ops(enc: &mut Encoder, ops: &[Json]) {
    for op in ops {
        encode_op(enc, op);
    }
}

fn encode_op(enc: &mut Encoder, op: &Json) {
    let ty = op.get("type").and_then(|t| t.as_str()).unwrap_or("");
    match ty {
        "bool" => enc.write_bool(op.get("bool").and_then(|v| v.as_bool()).unwrap_or(false)),
        "int32" => enc.write_int32(op.get("int32").and_then(|v| v.as_f64()).unwrap_or(0.0) as i64 as i32),
        "uint32" => {
            enc.write_uint32(op.get("uint32").and_then(|v| v.as_f64()).unwrap_or(0.0) as i64 as u32)
        }
        "int64" => {
            let s = op.get("int64").and_then(|v| v.as_str()).unwrap_or("0");
            enc.write_int64(s.parse().unwrap_or(0));
        }
        "uint64" => {
            let s = op.get("uint64").and_then(|v| v.as_str()).unwrap_or("0");
            enc.write_uint64(s.parse().unwrap_or(0));
        }
        "float32" => {
            let bits = u32::from_str_radix(
                strip_hex_prefix(op.get("floatBits").and_then(|v| v.as_str()).unwrap_or("0")),
                16,
            )
            .unwrap_or(0);
            enc.write_float32(f32::from_bits(bits));
        }
        "float64" => {
            let bits = u64::from_str_radix(
                strip_hex_prefix(op.get("floatBits").and_then(|v| v.as_str()).unwrap_or("0")),
                16,
            )
            .unwrap_or(0);
            enc.write_float64(f64::from_bits(bits));
        }
        "string" => enc.write_string(op.get("string").and_then(|v| v.as_str()).unwrap_or("")),
        "bytes" => {
            let b = hex_decode(op.get("bytes").and_then(|v| v.as_str()).unwrap_or(""));
            enc.write_bytes(&b);
        }
        "array" => {
            let elems = op.get("elems").map(|v| v.as_array()).unwrap_or(&[]);
            enc.write_int32(elems.len() as i32);
            for el in elems {
                encode_op(enc, el);
            }
        }
        "map" => {
            let entries = op.get("entries").map(|v| v.as_array()).unwrap_or(&[]);
            enc.write_int32(entries.len() as i32);
            for ent in entries {
                if let Some(k) = ent.get("k") {
                    encode_op(enc, k);
                }
                if let Some(v) = ent.get("v") {
                    encode_op(enc, v);
                }
            }
        }
        "message" => {
            let inner_ops = op.get("ops").map(|v| v.as_array()).unwrap_or(&[]);
            let mut inner = Encoder::new(64);
            encode_ops(&mut inner, inner_ops);
            let bytes = inner.finish();
            enc.write_message(&bytes);
        }
        other => panic!("unknown op type {other:?}"),
    }
}

// decode_ops reads every value, mirroring the decode-only work the Go driver
// and the other harnesses time. It does NOT verify the decoded values (so the
// decode column is consistent across runtimes); it returns a small accumulator
// so the optimizer cannot elide the decode in the timed loop. The op tree only
// supplies the structure (element/entry counts) to walk; the values come off
// the wire.
fn decode_ops(dec: &mut Decoder, ops: &[Json]) -> u64 {
    let mut acc = 0u64;
    for op in ops {
        acc = acc.wrapping_add(decode_op(dec, op));
    }
    acc
}

fn decode_op(dec: &mut Decoder, op: &Json) -> u64 {
    let ty = op.get("type").and_then(|t| t.as_str()).unwrap_or("");
    match ty {
        "bool" => dec.read_bool().expect("bool") as u64,
        "int32" => dec.read_int32().expect("int32") as u32 as u64,
        "uint32" => dec.read_uint32().expect("uint32") as u64,
        "int64" => dec.read_int64().expect("int64") as u64,
        "uint64" => dec.read_uint64().expect("uint64"),
        "float32" => dec.read_float32().expect("float32").to_bits() as u64,
        "float64" => dec.read_float64().expect("float64").to_bits(),
        "string" => dec.read_string().expect("string").len() as u64,
        "bytes" => dec.read_bytes().expect("bytes").len() as u64,
        "array" => {
            let count = dec.read_int32().expect("array count");
            let elems = op.get("elems").map(|v| v.as_array()).unwrap_or(&[]);
            let mut acc = count as u32 as u64;
            for el in elems {
                acc = acc.wrapping_add(decode_op(dec, el));
            }
            acc
        }
        "map" => {
            let count = dec.read_int32().expect("map count");
            let entries = op.get("entries").map(|v| v.as_array()).unwrap_or(&[]);
            let mut acc = count as u32 as u64;
            for ent in entries {
                if let Some(k) = ent.get("k") {
                    acc = acc.wrapping_add(decode_op(dec, k));
                }
                if let Some(v) = ent.get("v") {
                    acc = acc.wrapping_add(decode_op(dec, v));
                }
            }
            acc
        }
        "message" => {
            let msg = dec.read_message_bytes().expect("message");
            let inner_ops = op.get("ops").map(|v| v.as_array()).unwrap_or(&[]);
            let mut inner = Decoder::new(&msg);
            let acc = decode_ops(&mut inner, inner_ops);
            acc.wrapping_add(msg.len() as u64)
        }
        other => panic!("unknown op type {other:?}"),
    }
}

fn main() {
    let dir = match std::env::args().nth(1) {
        Some(d) => PathBuf::from(d),
        None => {
            eprintln!("usage: xpbench_rust <corpus-dir>");
            exit(2);
        }
    };
    let raw = fs::read_to_string(dir.join("vectors.json")).expect("read manifest");
    let manifest = Parser::new(&raw).value();
    let vectors = manifest.get("vectors").map(|v| v.as_array()).unwrap_or(&[]);
    if vectors.is_empty() {
        eprintln!("manifest has no vectors");
        exit(1);
    }

    let mut sink: u64 = 0;
    let mut out = String::from("[");
    for (vi, v) in vectors.iter().enumerate() {
        let name = v.get("name").and_then(|x| x.as_str()).unwrap_or("?");
        let file = v.get("file").and_then(|x| x.as_str()).unwrap_or("");
        let iters = v.get("iters").and_then(|x| x.as_f64()).unwrap_or(1.0).max(1.0) as u64;
        let ops = v.get("ops").map(|x| x.as_array()).unwrap_or(&[]);
        let data = fs::read(dir.join(file)).expect("read .bin");
        let wire = data.len();
        let warm = (iters / 10).max(1);

        // Encode timing.
        for _ in 0..warm {
            let mut enc = Encoder::new(256);
            encode_ops(&mut enc, ops);
            sink = sink.wrapping_add(enc.finish().len() as u64);
        }
        let t0 = Instant::now();
        for _ in 0..iters {
            let mut enc = Encoder::new(256);
            encode_ops(&mut enc, ops);
            sink = sink.wrapping_add(black_box(enc.finish().len() as u64));
        }
        let enc_ns = t0.elapsed().as_nanos() as f64 / iters as f64;

        // Decode timing.
        for _ in 0..warm {
            let mut dec = Decoder::new(&data);
            sink = sink.wrapping_add(decode_ops(&mut dec, ops));
        }
        let t1 = Instant::now();
        for _ in 0..iters {
            let mut dec = Decoder::new(&data);
            sink = sink.wrapping_add(black_box(decode_ops(&mut dec, ops)));
        }
        let dec_ns = t1.elapsed().as_nanos() as f64 / iters as f64;

        if vi > 0 {
            out.push(',');
        }
        out.push_str(&format!(
            "{{\"name\":\"{name}\",\"encodeNs\":{enc_ns:.3},\"decodeNs\":{dec_ns:.3},\"wireSize\":{wire}}}"
        ));
    }
    out.push(']');
    println!("{out}");
    // Keep the accumulator observable so the timed loops are not optimized away.
    if sink == u64::MAX {
        eprintln!("sink={sink}");
    }
}
