package lua

import (
	"fmt"
	"strings"

	xpbast "github.com/ElecTwix/xpb/pkg/ast"
	"github.com/ElecTwix/xpb/pkg/codegen/common"
)

func Generate(file *xpbast.File) ([]byte, error) {
	var sb strings.Builder
	ctx := xpbast.NewEnumSet(file)

	sb.WriteString("-- Code generated by xpbc. DO NOT EDIT.\n")
	sb.WriteString("-- luacheck: ignore\n\n")

	if file.Package != "" {
		sb.WriteString(fmt.Sprintf("-- Package: %s\n", file.Package))
	}

	sb.WriteString("local xpb = require 'xpb'\n\n")

	for _, enum := range file.Enums {
		writeEnum(&sb, enum)
	}

	for _, msg := range file.Messages {
		writeMessage(&sb, msg, file, ctx)
	}

	return []byte(sb.String()), nil
}

func luaMinWireBytes(t xpbast.FieldType) int {
	switch t.Kind {
	case xpbast.TypeBool:
		return 1
	case xpbast.TypeInt32, xpbast.TypeUint32, xpbast.TypeFloat32, xpbast.TypeEnum:
		return 4
	case xpbast.TypeInt64, xpbast.TypeUint64, xpbast.TypeFloat64:
		return 8
	case xpbast.TypeString, xpbast.TypeBytes, xpbast.TypeMessage:
		return 1
	}
	return 1
}

func luaReadCall(t xpbast.FieldType) string {
	switch t.Kind {
	case xpbast.TypeBool:
		return "dec:read_bool()"
	case xpbast.TypeInt32, xpbast.TypeEnum:
		return "dec:read_int32()"
	case xpbast.TypeInt64:
		return "dec:read_int64()"
	case xpbast.TypeUint32:
		return "dec:read_uint32()"
	case xpbast.TypeUint64:
		return "dec:read_uint64()"
	case xpbast.TypeFloat32:
		return "dec:read_float32()"
	case xpbast.TypeFloat64:
		return "dec:read_float64()"
	case xpbast.TypeString:
		return "dec:read_string()"
	case xpbast.TypeBytes:
		return "dec:read_bytes()"
	}
	return "nil"
}

func luaWriteCall(t xpbast.FieldType, expr string) string {
	switch t.Kind {
	case xpbast.TypeBool:
		return fmt.Sprintf("enc:write_bool(%s)", expr)
	case xpbast.TypeInt32, xpbast.TypeEnum:
		return fmt.Sprintf("enc:write_int32(%s)", expr)
	case xpbast.TypeInt64:
		return fmt.Sprintf("enc:write_int64(%s)", expr)
	case xpbast.TypeUint32:
		return fmt.Sprintf("enc:write_uint32(%s)", expr)
	case xpbast.TypeUint64:
		return fmt.Sprintf("enc:write_uint64(%s)", expr)
	case xpbast.TypeFloat32:
		return fmt.Sprintf("enc:write_float32(%s)", expr)
	case xpbast.TypeFloat64:
		return fmt.Sprintf("enc:write_float64(%s)", expr)
	case xpbast.TypeString:
		return fmt.Sprintf("enc:write_string(%s)", expr)
	case xpbast.TypeBytes:
		return fmt.Sprintf("enc:write_bytes(%s)", expr)
	}
	return ""
}

func writeEnum(sb *strings.Builder, enum *xpbast.Enum) {
	typeName := capitalize(enum.Name)
	sb.WriteString(fmt.Sprintf("-- %s enum\n", typeName))

	for _, v := range enum.Values {
		sb.WriteString(fmt.Sprintf("%s = %d\n", uppercaseFirst(v.Name), v.Number))
	}
	sb.WriteString(fmt.Sprintf("%s = {\n", typeName))
	for _, v := range enum.Values {
		sb.WriteString(fmt.Sprintf("    %s = %d,\n", uppercaseFirst(v.Name), v.Number))
	}
	sb.WriteString("}\n\n")
}

func writeMessage(sb *strings.Builder, msg *xpbast.Message, file *xpbast.File, ctx xpbast.EnumSet) {
	typeName := capitalize(msg.Name)
	hasOptional := false
	for _, f := range msg.Fields {
		if f.Optional {
			hasOptional = true
			break
		}
	}
	if hasOptional {
		sb.WriteString("-- NOTE: schema contains `optional` fields. Each optional field is\n")
		sb.WriteString("-- preceded on the wire by a 1-byte presence flag (0x01 present + value,\n")
		sb.WriteString("-- 0x00 absent). An absent optional decodes to nil.\n")
	}
	sb.WriteString(fmt.Sprintf("%s = {}\n", typeName))
	sb.WriteString(fmt.Sprintf("%s.__index = %s\n\n", typeName, typeName))

	for _, field := range msg.Fields {
		fieldName := lowercaseFirst(field.Name)
		sb.WriteString(fmt.Sprintf("%s.%s = nil\n", typeName, fieldName))
	}
	sb.WriteString("\n")

	writeNewMethod(sb, msg, typeName)
	writeMarshalMethod(sb, msg, typeName, file, ctx)
	writeUnmarshalMethod(sb, msg, typeName, file, ctx)

	sb.WriteString(fmt.Sprintf("return %s\n\n", typeName))
}

func writeNewMethod(sb *strings.Builder, msg *xpbast.Message, typeName string) {
	sb.WriteString(fmt.Sprintf("function %s.new()\n", typeName))
	sb.WriteString(fmt.Sprintf("    local self = setmetatable({}, %s)\n", typeName))
	for _, field := range msg.Fields {
		fieldName := lowercaseFirst(field.Name)
		defaultValue := getDefaultValue(field.Type)
		sb.WriteString(fmt.Sprintf("    self.%s = %s\n", fieldName, defaultValue))
	}
	sb.WriteString("    return self\n")
	sb.WriteString("end\n\n")
}

func writeMarshalMethod(sb *strings.Builder, msg *xpbast.Message, typeName string, file *xpbast.File, ctx xpbast.EnumSet) {
	sb.WriteString(fmt.Sprintf("function %s:Marshal()\n", typeName))
	sb.WriteString("    local enc = xpb.Encoder(64)\n")

	for _, field := range msg.Fields {
		fieldName := lowercaseFirst(field.Name)
		ref := "self." + fieldName
		if field.Optional && !field.Repeated && field.Type.Kind != xpbast.TypeMap {
			writeLuaOptionalFieldEncode(sb, field, ref, ctx)
			continue
		}
		// Enum fields hold their numeric value directly in the table.
		if ctx.IsEnum(field.Type) && !field.Repeated {
			sb.WriteString(fmt.Sprintf("    enc:write_int32(%s)\n", ref))
			continue
		}
		if field.Repeated {
			writeLuaRepeatedFieldEncode(sb, field, ref, ctx)
			continue
		}
		if field.Type.Kind == xpbast.TypeMap {
			writeLuaMapFieldEncode(sb, field, ref)
			continue
		}
		if field.Type.Kind == xpbast.TypeMessage {
			sb.WriteString(fmt.Sprintf("    enc:write_message(%s:Marshal())\n", ref))
			continue
		}
		sb.WriteString(fmt.Sprintf("    %s\n", luaWriteCall(field.Type, ref)))
	}

	sb.WriteString("    return enc:finish()\n")
	sb.WriteString("end\n\n")
}

func writeUnmarshalMethod(sb *strings.Builder, msg *xpbast.Message, typeName string, file *xpbast.File, ctx xpbast.EnumSet) {
	// Public entry point delegates to the depth-threaded helper. The
	// generated UnmarshalAt(data, depth) checks against MAX_DECODE_DEPTH
	// before doing anything, so a hand-crafted recursive payload can't
	// drive the Lua C stack into a fatal overflow.
	sb.WriteString(fmt.Sprintf("function %s.Unmarshal(data)\n", typeName))
	sb.WriteString(fmt.Sprintf("    return %s.UnmarshalAt(data, 0)\n", typeName))
	sb.WriteString("end\n\n")

	sb.WriteString(fmt.Sprintf("function %s.UnmarshalAt(data, depth)\n", typeName))
	sb.WriteString("    if depth > xpb.MAX_DECODE_DEPTH then\n")
	sb.WriteString("        error('xpb: max decode depth exceeded', 2)\n")
	sb.WriteString("    end\n")
	sb.WriteString("    local dec = xpb.Decoder(data)\n")
	sb.WriteString(fmt.Sprintf("    local self = setmetatable({}, %s)\n", typeName))

	for _, field := range msg.Fields {
		fieldName := lowercaseFirst(field.Name)
		if field.Optional && !field.Repeated && field.Type.Kind != xpbast.TypeMap {
			writeLuaOptionalFieldDecode(sb, field, fieldName, ctx)
			continue
		}
		if ctx.IsEnum(field.Type) && !field.Repeated {
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_int32()\n", fieldName))
			continue
		}
		if field.Repeated {
			writeLuaRepeatedFieldDecode(sb, field, fieldName, ctx)
			continue
		}
		if field.Type.Kind == xpbast.TypeMap {
			writeLuaMapFieldDecode(sb, field, fieldName)
			continue
		}
		if field.Type.Kind == xpbast.TypeMessage {
			sb.WriteString(fmt.Sprintf("    self.%s = %s.UnmarshalAt(dec:read_message_bytes(), depth + 1)\n",
				fieldName, capitalize(field.Type.Message)))
			continue
		}
		sb.WriteString(fmt.Sprintf("    self.%s = %s\n", fieldName, luaReadCall(field.Type)))
	}

	sb.WriteString("    return self\n")
	sb.WriteString("end\n\n")
}

func writeLuaRepeatedFieldEncode(sb *strings.Builder, field *xpbast.Field, ref string, ctx xpbast.EnumSet) {
	sb.WriteString(fmt.Sprintf("    do\n"))
	sb.WriteString(fmt.Sprintf("        local arr = %s or {}\n", ref))
	sb.WriteString("        enc:write_int32(#arr)\n")
	sb.WriteString("        for _, v in ipairs(arr) do\n")
	if ctx.IsEnum(field.Type) {
		sb.WriteString("            enc:write_int32(v)\n")
	} else if field.Type.Kind == xpbast.TypeMessage {
		sb.WriteString("            enc:write_message(v:Marshal())\n")
	} else {
		sb.WriteString(fmt.Sprintf("            %s\n", luaWriteCall(field.Type, "v")))
	}
	sb.WriteString("        end\n")
	sb.WriteString("    end\n")
}

func writeLuaMapFieldEncode(sb *strings.Builder, field *xpbast.Field, ref string) {
	sb.WriteString(fmt.Sprintf("    do\n"))
	sb.WriteString(fmt.Sprintf("        local m = %s or {}\n", ref))
	sb.WriteString("        local n = 0; for _ in pairs(m) do n = n + 1 end\n")
	sb.WriteString("        enc:write_int32(n)\n")
	sb.WriteString("        for k, v in pairs(m) do\n")
	sb.WriteString(fmt.Sprintf("            %s\n", luaWriteCall(*field.Type.KeyType, "k")))
	sb.WriteString(fmt.Sprintf("            %s\n", luaWriteCall(*field.Type.ValType, "v")))
	sb.WriteString("        end\n")
	sb.WriteString("    end\n")
}

func writeLuaRepeatedFieldDecode(sb *strings.Builder, field *xpbast.Field, fieldName string, ctx xpbast.EnumSet) {
	min := luaMinWireBytes(field.Type)
	if ctx.IsEnum(field.Type) {
		min = 4
	}
	sb.WriteString("    do\n")
	sb.WriteString(fmt.Sprintf("        local count = dec:read_array_count(%d, %d)\n",
		min, common.DefaultMaxElements))
	sb.WriteString(fmt.Sprintf("        self.%s = {}\n", fieldName))
	sb.WriteString("        for i = 1, count do\n")
	if ctx.IsEnum(field.Type) {
		sb.WriteString(fmt.Sprintf("            self.%s[i] = dec:read_int32()\n", fieldName))
	} else if field.Type.Kind == xpbast.TypeMessage {
		sb.WriteString(fmt.Sprintf("            self.%s[i] = %s.UnmarshalAt(dec:read_message_bytes(), depth + 1)\n",
			fieldName, capitalize(field.Type.Message)))
	} else {
		sb.WriteString(fmt.Sprintf("            self.%s[i] = %s\n", fieldName, luaReadCall(field.Type)))
	}
	sb.WriteString("        end\n")
	sb.WriteString("    end\n")
}

func writeLuaMapFieldDecode(sb *strings.Builder, field *xpbast.Field, fieldName string) {
	keyMin := luaMinWireBytes(*field.Type.KeyType)
	valMin := luaMinWireBytes(*field.Type.ValType)
	sb.WriteString("    do\n")
	sb.WriteString(fmt.Sprintf("        local count = dec:read_array_count(%d, %d)\n",
		keyMin+valMin, common.DefaultMaxElements))
	sb.WriteString(fmt.Sprintf("        self.%s = {}\n", fieldName))
	sb.WriteString("        for i = 1, count do\n")
	sb.WriteString(fmt.Sprintf("            local k = %s\n", luaReadCall(*field.Type.KeyType)))
	sb.WriteString(fmt.Sprintf("            local v = %s\n", luaReadCall(*field.Type.ValType)))
	sb.WriteString(fmt.Sprintf("            self.%s[k] = v\n", fieldName))
	sb.WriteString("        end\n")
	sb.WriteString("    end\n")
}

// writeLuaOptionalFieldEncode emits the 1-byte presence flag (see
// docs/WIRE_FORMAT.md) followed by the value only when the field is non-nil.
func writeLuaOptionalFieldEncode(sb *strings.Builder, field *xpbast.Field, ref string, ctx xpbast.EnumSet) {
	sb.WriteString(fmt.Sprintf("    enc:write_bool(%s ~= nil)\n", ref))
	sb.WriteString(fmt.Sprintf("    if %s ~= nil then\n", ref))
	if ctx.IsEnum(field.Type) {
		sb.WriteString(fmt.Sprintf("        enc:write_int32(%s)\n", ref))
	} else if field.Type.Kind == xpbast.TypeMessage {
		sb.WriteString(fmt.Sprintf("        enc:write_message(%s:Marshal())\n", ref))
	} else {
		sb.WriteString(fmt.Sprintf("        %s\n", luaWriteCall(field.Type, ref)))
	}
	sb.WriteString("    end\n")
}

// writeLuaOptionalFieldDecode reads the presence flag and only reads the value
// when present; otherwise the field stays nil and exactly 1 byte is consumed.
func writeLuaOptionalFieldDecode(sb *strings.Builder, field *xpbast.Field, fieldName string, ctx xpbast.EnumSet) {
	sb.WriteString("    if dec:read_bool() then\n")
	if ctx.IsEnum(field.Type) {
		sb.WriteString(fmt.Sprintf("        self.%s = dec:read_int32()\n", fieldName))
	} else if field.Type.Kind == xpbast.TypeMessage {
		sb.WriteString(fmt.Sprintf("        self.%s = %s.UnmarshalAt(dec:read_message_bytes(), depth + 1)\n",
			fieldName, capitalize(field.Type.Message)))
	} else {
		sb.WriteString(fmt.Sprintf("        self.%s = %s\n", fieldName, luaReadCall(field.Type)))
	}
	sb.WriteString("    end\n")
}

func getDefaultValue(t xpbast.FieldType) string {
	switch t.Kind {
	case xpbast.TypeBool:
		return "false"
	case xpbast.TypeInt32, xpbast.TypeInt64:
		return "0"
	case xpbast.TypeUint32, xpbast.TypeUint64:
		return "0"
	case xpbast.TypeFloat32, xpbast.TypeFloat64:
		return "0.0"
	case xpbast.TypeString:
		return "\"\""
	case xpbast.TypeBytes:
		return "\"\""
	default:
		return "nil"
	}
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func lowercaseFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func uppercaseFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
