package lua

import (
	"fmt"
	"strings"

	xpbast "github.com/anthropic/xpb/pkg/ast"
)

func Generate(file *xpbast.File) ([]byte, error) {
	var sb strings.Builder

	sb.WriteString("-- Code generated by xpbc. DO NOT EDIT.\n")
	sb.WriteString("-- luacheck: ignore\n\n")

	if file.Package != "" {
		sb.WriteString(fmt.Sprintf("-- Package: %s\n", file.Package))
	}

	sb.WriteString("local xpb = require 'xpb'\n\n")

	for _, enum := range file.Enums {
		writeEnum(&sb, enum)
	}

	for _, msg := range file.Messages {
		writeMessage(&sb, msg, file)
	}

	return []byte(sb.String()), nil
}

func writeEnum(sb *strings.Builder, enum *xpbast.Enum) {
	typeName := capitalize(enum.Name)
	sb.WriteString(fmt.Sprintf("-- %s enum\n", typeName))

	for _, v := range enum.Values {
		sb.WriteString(fmt.Sprintf("%s = %d\n", uppercaseFirst(v.Name), v.Number))
	}
	sb.WriteString(fmt.Sprintf("%s = {\n", typeName))
	for _, v := range enum.Values {
		sb.WriteString(fmt.Sprintf("    %s = %d,\n", uppercaseFirst(v.Name), v.Number))
	}
	sb.WriteString("}\n\n")
}

func writeMessage(sb *strings.Builder, msg *xpbast.Message, file *xpbast.File) {
	typeName := capitalize(msg.Name)
	sb.WriteString(fmt.Sprintf("%s = {}\n", typeName))
	sb.WriteString(fmt.Sprintf("%s.__index = %s\n\n", typeName, typeName))

	for _, field := range msg.Fields {
		fieldName := lowercaseFirst(field.Name)
		sb.WriteString(fmt.Sprintf("%s.%s = nil\n", typeName, fieldName))
	}
	sb.WriteString("\n")

	writeNewMethod(sb, msg, typeName)
	writeMarshalMethod(sb, msg, typeName, file)
	writeUnmarshalMethod(sb, msg, typeName, file)

	sb.WriteString(fmt.Sprintf("return %s\n\n", typeName))
}

func writeNewMethod(sb *strings.Builder, msg *xpbast.Message, typeName string) {
	sb.WriteString(fmt.Sprintf("function %s.new()\n", typeName))
	sb.WriteString(fmt.Sprintf("    local self = setmetatable({}, %s)\n", typeName))
	for _, field := range msg.Fields {
		fieldName := lowercaseFirst(field.Name)
		defaultValue := getDefaultValue(field.Type)
		sb.WriteString(fmt.Sprintf("    self.%s = %s\n", fieldName, defaultValue))
	}
	sb.WriteString("    return self\n")
	sb.WriteString("end\n\n")
}

func writeMarshalMethod(sb *strings.Builder, msg *xpbast.Message, typeName string, file *xpbast.File) {
	sb.WriteString(fmt.Sprintf("function %s:Marshal()\n", typeName))
	sb.WriteString("    local enc = xpb.Encoder(64)\n")

	for _, field := range msg.Fields {
		fieldName := lowercaseFirst(field.Name)
		switch field.Type.Kind {
		case xpbast.TypeBool:
			sb.WriteString(fmt.Sprintf("    enc:write_bool(self.%s)\n", fieldName))
		case xpbast.TypeInt32:
			sb.WriteString(fmt.Sprintf("    enc:write_int32(self.%s)\n", fieldName))
		case xpbast.TypeInt64:
			sb.WriteString(fmt.Sprintf("    enc:write_int64(self.%s)\n", fieldName))
		case xpbast.TypeUint32:
			sb.WriteString(fmt.Sprintf("    enc:write_uint32(self.%s)\n", fieldName))
		case xpbast.TypeUint64:
			sb.WriteString(fmt.Sprintf("    enc:write_uint64(self.%s)\n", fieldName))
		case xpbast.TypeFloat32:
			sb.WriteString(fmt.Sprintf("    enc:write_float32(self.%s)\n", fieldName))
		case xpbast.TypeFloat64:
			sb.WriteString(fmt.Sprintf("    enc:write_float64(self.%s)\n", fieldName))
		case xpbast.TypeString:
			sb.WriteString(fmt.Sprintf("    enc:write_string(self.%s)\n", fieldName))
		case xpbast.TypeBytes:
			sb.WriteString(fmt.Sprintf("    enc:write_bytes(self.%s)\n", fieldName))
		case xpbast.TypeMessage:
			sb.WriteString(fmt.Sprintf("    enc:write_message(self.%s:Marshal())\n", fieldName))
		case xpbast.TypeEnum:
			sb.WriteString(fmt.Sprintf("    enc:write_int32(self.%s)\n", fieldName))
		}
	}

	sb.WriteString("    return enc:finish()\n")
	sb.WriteString("end\n\n")
}

func writeUnmarshalMethod(sb *strings.Builder, msg *xpbast.Message, typeName string, file *xpbast.File) {
	sb.WriteString(fmt.Sprintf("function %s.Unmarshal(data)\n", typeName))
	sb.WriteString("    local dec = xpb.Decoder(data)\n")
	sb.WriteString(fmt.Sprintf("    local self = setmetatable({}, %s)\n", typeName))

	for _, field := range msg.Fields {
		fieldName := lowercaseFirst(field.Name)
		switch field.Type.Kind {
		case xpbast.TypeBool:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_bool()\n", fieldName))
		case xpbast.TypeInt32:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_int32()\n", fieldName))
		case xpbast.TypeInt64:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_int64()\n", fieldName))
		case xpbast.TypeUint32:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_uint32()\n", fieldName))
		case xpbast.TypeUint64:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_uint64()\n", fieldName))
		case xpbast.TypeFloat32:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_float32()\n", fieldName))
		case xpbast.TypeFloat64:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_float64()\n", fieldName))
		case xpbast.TypeString:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_string()\n", fieldName))
		case xpbast.TypeBytes:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_bytes()\n", fieldName))
		case xpbast.TypeMessage:
			sb.WriteString(fmt.Sprintf("    self.%s = %s:Unmarshal(dec:read_message_bytes())\n",
				fieldName, capitalize(field.Type.Message)))
		case xpbast.TypeEnum:
			sb.WriteString(fmt.Sprintf("    self.%s = dec:read_int32()\n", fieldName))
		}
	}

	sb.WriteString("    return self\n")
	sb.WriteString("end\n\n")
}

func getDefaultValue(t xpbast.FieldType) string {
	switch t.Kind {
	case xpbast.TypeBool:
		return "false"
	case xpbast.TypeInt32, xpbast.TypeInt64:
		return "0"
	case xpbast.TypeUint32, xpbast.TypeUint64:
		return "0"
	case xpbast.TypeFloat32, xpbast.TypeFloat64:
		return "0.0"
	case xpbast.TypeString:
		return "\"\""
	case xpbast.TypeBytes:
		return "\"\""
	default:
		return "nil"
	}
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func lowercaseFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func uppercaseFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
