// Package typescript generates TypeScript code from XPB schemas.
package typescript

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/ElecTwix/xpb/pkg/ast"
	"github.com/ElecTwix/xpb/pkg/codegen/common"
)

// Generator generates TypeScript code from an AST.
type Generator struct {
	buf   bytes.Buffer
	enums ast.EnumSet
}

// Generate generates TypeScript code for the given file AST.
func Generate(file *ast.File) ([]byte, error) {
	g := &Generator{enums: ast.NewEnumSet(file)}
	return g.generate(file)
}

func (g *Generator) generate(file *ast.File) ([]byte, error) {
	g.buf.Reset()

	g.printf("// Code generated by xpbc. DO NOT EDIT.\n\n")
	g.printf("import { Encoder, Decoder, MaxDecodeDepth, MaxDecodeDepthExceededError } from '@xpb/runtime';\n\n")

	// Generate enums
	for _, enum := range file.Enums {
		g.generateEnum(enum)
	}

	// Generate messages
	for _, msg := range file.Messages {
		g.generateMessage(msg)
	}

	return g.buf.Bytes(), nil
}

func (g *Generator) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) generateEnum(enum *ast.Enum) {
	name := enum.Name
	g.printf("export enum %s {\n", name)
	for _, v := range enum.Values {
		g.printf("  %s = %d,\n", v.Name, v.Number)
	}
	g.printf("}\n\n")
}

func (g *Generator) generateMessage(msg *ast.Message) {
	name := msg.Name

	hasOptional := false
	for _, f := range msg.Fields {
		if f.Optional {
			hasOptional = true
			break
		}
	}
	if hasOptional {
		g.printf("// NOTE: schema contains `optional` fields. The XPB V2 wire format has no\n")
		g.printf("// presence bit, so this codegen emits them as required on the wire.\n")
		g.printf("// Callers must agree on a sentinel value (or upgrade to V3) before\n")
		g.printf("// relying on optional semantics.\n")
	}

	// Interface
	g.printf("export interface %sData {\n", name)
	for _, field := range msg.Fields {
		tsType := tsTypeName(field)
		fieldName := toCamelCaseTS(field.Name)
		if field.Optional {
			g.printf("  %s?: %s;\n", fieldName, tsType)
		} else {
			g.printf("  %s: %s;\n", fieldName, tsType)
		}
	}
	g.printf("}\n\n")

	// Class
	g.printf("export class %s implements %sData {\n", name, name)
	for _, field := range msg.Fields {
		tsType := tsTypeName(field)
		fieldName := toCamelCaseTS(field.Name)
		if field.Optional {
			g.printf("  %s?: %s;\n", fieldName, tsType)
		} else if field.Repeated {
			g.printf("  %s: %s = [];\n", fieldName, tsType)
		} else if field.Type.Kind == ast.TypeMap {
			g.printf("  %s: %s = new Map();\n", fieldName, tsType)
		} else {
			g.printf("  %s!: %s;\n", fieldName, tsType)
		}
	}
	g.printf("\n")

	// Constructor — assigns each schema-declared field explicitly. Object.assign
	// would happily walk a `__proto__` own property and pollute the prototype
	// chain (e.g. `new Foo(JSON.parse('{"__proto__":{"isAdmin":true}}'))`).
	// Naming every field here means only declared field names are copied
	// from `data`, and the prototype is untouched regardless of input.
	g.printf("  constructor(data: Partial<%sData> = {}) {\n", name)
	for _, field := range msg.Fields {
		fieldName := toCamelCaseTS(field.Name)
		if field.Repeated {
			g.printf("    if (data.%s !== undefined) this.%s = data.%s;\n", fieldName, fieldName, fieldName)
		} else if field.Type.Kind == ast.TypeMap {
			g.printf("    if (data.%s !== undefined) this.%s = data.%s;\n", fieldName, fieldName, fieldName)
		} else {
			g.printf("    if (data.%s !== undefined) this.%s = data.%s;\n", fieldName, fieldName, fieldName)
		}
	}
	g.printf("  }\n\n")

	// Encode
	g.printf("  static encode(msg: %sData): Uint8Array {\n", name)
	g.printf("    const enc = new Encoder();\n")
	// V2: Encode fields in order, no tags
	for _, field := range msg.Fields {
		g.generateFieldEncodeTS(field)
	}
	g.printf("    return enc.finish();\n")
	g.printf("  }\n\n")

	// Decode
	g.printf("  static decode(data: Uint8Array): %s {\n", name)
	g.printf("    return %s.decodeAt(data, 0);\n", name)
	g.printf("  }\n\n")

	g.printf("  static decodeAt(data: Uint8Array, depth: number): %s {\n", name)
	g.printf("    if (depth > MaxDecodeDepth) { throw new MaxDecodeDepthExceededError(); }\n")
	g.printf("    const dec = new Decoder(data);\n")
	g.printf("    const msg = new %s();\n", name)
	// V2: Decode fields in order, no switch/tags
	for _, field := range msg.Fields {
		g.generateFieldDecodeTS(field)
	}
	g.printf("    return msg;\n")
	g.printf("  }\n\n")

	// Instance encode
	g.printf("  encode(): Uint8Array {\n")
	g.printf("    return %s.encode(this);\n", name)
	g.printf("  }\n")

	g.printf("}\n\n")
}

func (g *Generator) generateFieldEncodeTS(field *ast.Field) {
	fieldName := toCamelCaseTS(field.Name)

	// Repeated
	if field.Repeated {
		g.printf("    enc.writeInt32(msg.%s?.length ?? 0);\n", fieldName)
		g.printf("    for (const v of msg.%s ?? []) {\n", fieldName)
		g.generateScalarEncodeTS("v", field.Type, "      ")
		g.printf("    }\n")
		return
	}

	// Map
	if field.Type.Kind == ast.TypeMap {
		g.printf("    enc.writeInt32(msg.%s?.size ?? 0);\n", fieldName)
		g.printf("    for (const [k, v] of msg.%s ?? []) {\n", fieldName)
		g.generateScalarEncodeTS("k", *field.Type.KeyType, "      ")
		g.generateScalarEncodeTS("v", *field.Type.ValType, "      ")
		g.printf("    }\n")
		return
	}

	g.generateScalarEncodeTS("msg."+fieldName, field.Type, "    ")
}

func (g *Generator) generateScalarEncodeTS(varName string, t ast.FieldType, indent string) {
	// Enums parse as TypeMessage when referenced by name; resolve them
	// here before hitting the message branch (which would emit
	// `Enum.encode(v)` — a method that doesn't exist on a TS enum).
	if g.enums.IsEnum(t) {
		g.printf("%senc.writeInt32(%s);\n", indent, varName)
		return
	}

	switch t.Kind {
	case ast.TypeBool:
		g.printf("%senc.writeBool(%s);\n", indent, varName)
	case ast.TypeInt32, ast.TypeEnum:
		g.printf("%senc.writeInt32(%s);\n", indent, varName)
	case ast.TypeInt64:
		g.printf("%senc.writeInt64(BigInt(%s));\n", indent, varName)
	case ast.TypeUint32:
		g.printf("%senc.writeUint32(%s);\n", indent, varName)
	case ast.TypeUint64:
		g.printf("%senc.writeUint64(BigInt(%s));\n", indent, varName)
	case ast.TypeFloat32:
		g.printf("%senc.writeFloat32(%s);\n", indent, varName)
	case ast.TypeFloat64:
		g.printf("%senc.writeFloat64(%s);\n", indent, varName)
	case ast.TypeString:
		g.printf("%senc.writeString(%s ?? \"\");\n", indent, varName)
	case ast.TypeBytes:
		g.printf("%senc.writeBytes(%s ?? new Uint8Array(0));\n", indent, varName)
	case ast.TypeMessage:
		// V2 Message: length prefix + encoded bytes. A null/undefined
		// value (an absent optional field or a nullish entry inside a
		// repeated/map array) would throw inside Klass.encode at the
		// nested type's first writeBytes/writeString. Emit a 0-length
		// envelope instead — symmetric with the decode-side guard that
		// skips decodeAt on `_data.length > 0`.
		g.printf("%senc.writeMessage(%s != null ? %s.encode(%s) : new Uint8Array(0));\n", indent, varName, t.Message, varName)
	}
}

func (g *Generator) generateFieldDecodeTS(field *ast.Field) {
	fieldName := toCamelCaseTS(field.Name)

	// Repeated
	if field.Repeated {
		elemMin := g.tsMinWireBytes(field.Type)
		g.printf("    {\n")
		g.printf("      const count = dec.readArrayCount(%d, %d);\n", elemMin, common.DefaultMaxElements)
		g.printf("      msg.%s = new Array(count);\n", fieldName)
		g.printf("      for (let i = 0; i < count; i++) {\n")
		g.generateScalarDecodeTS(fieldName, field.Type, "        ", true, false)
		g.printf("      }\n")
		g.printf("    }\n")
		return
	}

	// Map
	if field.Type.Kind == ast.TypeMap {
		keyMin := g.tsMinWireBytes(*field.Type.KeyType)
		valMin := g.tsMinWireBytes(*field.Type.ValType)
		g.printf("    {\n")
		g.printf("      const count = dec.readArrayCount(%d, %d);\n", keyMin+valMin, common.DefaultMaxElements)
		g.printf("      msg.%s = new Map();\n", fieldName)
		g.printf("      for (let i = 0; i < count; i++) {\n")
		g.printf("        let k: %s;\n", tsBaseTypeName(*field.Type.KeyType))
		g.printf("        let v: %s;\n", tsBaseTypeName(*field.Type.ValType))

		// Read key
		g.generateScalarDecodeTS("k", *field.Type.KeyType, "        ", false, true)
		// Read value
		g.generateScalarDecodeTS("v", *field.Type.ValType, "        ", false, true)

		g.printf("        msg.%s.set(k!, v!);\n", fieldName)
		g.printf("      }\n")
		g.printf("    }\n")
		return
	}

	// Regular
	g.generateScalarDecodeTS(fieldName, field.Type, "    ", false, false)
}

func (g *Generator) generateScalarDecodeTS(target string, t ast.FieldType, indent string, isRepeated bool, isLocalVar bool) {
	lhs := ""
	if isLocalVar {
		lhs = target
	} else if isRepeated {
		lhs = fmt.Sprintf("msg.%s[i]", target)
	} else {
		lhs = fmt.Sprintf("msg.%s", target)
	}

	// Nested-message fields need special handling so a 0-length envelope
	// (an absent/null nested message) doesn't trigger a throw inside
	// the nested type's decodeAt at its first scalar read. Read the
	// bytes into a local var and skip the recursive decodeAt when
	// empty — the target stays unassigned, which is symmetric with
	// what a caller of the encode side would produce when the field
	// is null/undefined. We must resolve enums-as-messages first since
	// they share the TypeMessage tag at this layer.
	if t.Kind == ast.TypeMessage && !g.enums.IsEnum(t) {
		g.printf("%s{\n", indent)
		g.printf("%s  const _data = dec.readMessageBytes();\n", indent)
		g.printf("%s  if (_data.length > 0) %s = %s.decodeAt(_data, depth+1);\n", indent, lhs, t.Message)
		g.printf("%s}\n", indent)
		return
	}

	readExpr := g.tsReadCall(t)
	g.printf("%s%s = %s;\n", indent, lhs, readExpr)
}

func (g *Generator) tsReadCall(t ast.FieldType) string {
	// Resolve enum-as-message before falling through to the message
	// branch (which would emit `Enum.decodeAt(...)` — a method that
	// doesn't exist on a TS enum).
	if g.enums.IsEnum(t) {
		return "dec.readInt32()"
	}
	switch t.Kind {
	case ast.TypeBool:
		return "dec.readBool()"
	case ast.TypeInt32, ast.TypeEnum:
		return "dec.readInt32()"
	case ast.TypeInt64:
		return "dec.readInt64()"
	case ast.TypeUint32:
		return "dec.readUint32()"
	case ast.TypeUint64:
		return "dec.readUint64()"
	case ast.TypeFloat32:
		return "dec.readFloat32()"
	case ast.TypeFloat64:
		return "dec.readFloat64()"
	case ast.TypeString:
		return "dec.readString()"
	case ast.TypeBytes:
		return "dec.readBytes()"
	case ast.TypeMessage:
		return fmt.Sprintf("%s.decodeAt(dec.readMessageBytes(), depth+1)", t.Message)
	default:
		return "null as any"
	}
}

func tsTypeName(field *ast.Field) string {
	t := field.Type
	base := tsBaseTypeName(t)

	if field.Repeated {
		return base + "[]"
	}
	if t.Kind == ast.TypeMap {
		return fmt.Sprintf("Map<%s, %s>", tsBaseTypeName(*t.KeyType), tsBaseTypeName(*t.ValType))
	}
	return base
}

func tsBaseTypeName(t ast.FieldType) string {
	switch t.Kind {
	case ast.TypeBool:
		return "boolean"
	case ast.TypeInt32, ast.TypeUint32, ast.TypeFloat32, ast.TypeFloat64, ast.TypeEnum:
		return "number"
	case ast.TypeInt64, ast.TypeUint64:
		return "bigint"
	case ast.TypeString:
		return "string"
	case ast.TypeBytes:
		return "Uint8Array"
	case ast.TypeMessage:
		return t.Message
	default:
		return "unknown"
	}
}

// tsMinWireBytes returns the smallest possible on-wire size for one element
// of the given type. Used to bound the count of a repeated/map field against
// the remaining buffer in readArrayCount. Enum-references-as-TypeMessage
// resolve to 4 bytes (the int32 the wire actually carries).
func (g *Generator) tsMinWireBytes(t ast.FieldType) int {
	if g.enums.IsEnum(t) {
		return 4
	}
	switch t.Kind {
	case ast.TypeBool:
		return 1
	case ast.TypeInt32, ast.TypeUint32, ast.TypeFloat32, ast.TypeEnum:
		return 4
	case ast.TypeInt64, ast.TypeUint64, ast.TypeFloat64:
		return 8
	case ast.TypeString, ast.TypeBytes, ast.TypeMessage:
		return 1
	}
	return 1
}

func toCamelCaseTS(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
