// Package typescript generates TypeScript code from XPB schemas.
package typescript

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/anthropic/xpb/pkg/ast"
)

// Generator generates TypeScript code from an AST.
type Generator struct {
	buf bytes.Buffer
}

// Generate generates TypeScript code for the given file AST.
func Generate(file *ast.File) ([]byte, error) {
	g := &Generator{}
	return g.generate(file)
}

func (g *Generator) generate(file *ast.File) ([]byte, error) {
	g.buf.Reset()

	g.printf("// Code generated by xpbc. DO NOT EDIT.\n\n")
	g.printf("import { Encoder, Decoder, WireType } from '@xpb/runtime';\n\n")

	// Generate enums
	for _, enum := range file.Enums {
		g.generateEnum(enum)
	}

	// Generate messages
	for _, msg := range file.Messages {
		g.generateMessage(msg)
	}

	return g.buf.Bytes(), nil
}

func (g *Generator) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) generateEnum(enum *ast.Enum) {
	name := enum.Name
	g.printf("export enum %s {\n", name)
	for _, v := range enum.Values {
		g.printf("  %s = %d,\n", v.Name, v.Number)
	}
	g.printf("}\n\n")
}

func (g *Generator) generateMessage(msg *ast.Message) {
	name := msg.Name

	// Interface
	g.printf("export interface %sData {\n", name)
	for _, field := range msg.Fields {
		tsType := tsTypeName(field)
		fieldName := toCamelCaseTS(field.Name)
		if field.Optional {
			g.printf("  %s?: %s;\n", fieldName, tsType)
		} else {
			g.printf("  %s: %s;\n", fieldName, tsType)
		}
	}
	g.printf("}\n\n")

	// Class
	g.printf("export class %s implements %sData {\n", name, name)
	for _, field := range msg.Fields {
		tsType := tsTypeName(field)
		fieldName := toCamelCaseTS(field.Name)
		if field.Optional {
			g.printf("  %s?: %s;\n", fieldName, tsType)
		} else if field.Repeated {
			g.printf("  %s: %s = [];\n", fieldName, tsType)
		} else if field.Type.Kind == ast.TypeMap {
			g.printf("  %s: %s = new Map();\n", fieldName, tsType)
		} else {
			g.printf("  %s!: %s;\n", fieldName, tsType)
		}
	}
	g.printf("\n")

	// Constructor
	g.printf("  constructor(data: Partial<%sData> = {}) {\n", name)
	g.printf("    Object.assign(this, data);\n")
	g.printf("  }\n\n")

	// Encode
	g.printf("  static encode(msg: %sData): Uint8Array {\n", name)
	g.printf("    const enc = new Encoder();\n")
	for _, field := range msg.Fields {
		g.generateFieldEncodeTS(field)
	}
	g.printf("    return enc.finish();\n")
	g.printf("  }\n\n")

	// Decode
	g.printf("  static decode(data: Uint8Array): %s {\n", name)
	g.printf("    const dec = new Decoder(data);\n")
	g.printf("    const msg = new %s();\n", name)
	g.printf("    while (!dec.eof()) {\n")
	g.printf("      const [fieldNum, wireType] = dec.readTag();\n")
	g.printf("      switch (fieldNum) {\n")
	for _, field := range msg.Fields {
		g.generateFieldDecodeTS(field)
	}
	g.printf("        default:\n")
	g.printf("          dec.skip(wireType);\n")
	g.printf("      }\n")
	g.printf("    }\n")
	g.printf("    return msg;\n")
	g.printf("  }\n\n")

	// Instance encode
	g.printf("  encode(): Uint8Array {\n")
	g.printf("    return %s.encode(this);\n", name)
	g.printf("  }\n")

	g.printf("}\n\n")
}

func (g *Generator) generateFieldEncodeTS(field *ast.Field) {
	fieldName := toCamelCaseTS(field.Name)
	fieldNum := field.Number

	// Repeated
	if field.Repeated {
		g.printf("    for (const v of msg.%s ?? []) {\n", fieldName)
		g.generateScalarEncodeTS("v", fieldNum, field.Type, "      ")
		g.printf("    }\n")
		return
	}

	// Map
	if field.Type.Kind == ast.TypeMap {
		g.printf("    for (const [k, v] of msg.%s ?? []) {\n", fieldName)
		g.printf("      const mapEnc = new Encoder();\n")
		g.generateScalarEncodeTS("k", 1, *field.Type.KeyType, "      ")
		g.generateScalarEncodeTS("v", 2, *field.Type.ValType, "      ")
		g.printf("      enc.writeMessage(%d, mapEnc.finish());\n", fieldNum)
		g.printf("    }\n")
		return
	}

	// Optional
	if field.Optional {
		g.printf("    if (msg.%s !== undefined) {\n", fieldName)
		g.generateScalarEncodeTS("msg."+fieldName, fieldNum, field.Type, "      ")
		g.printf("    }\n")
		return
	}

	// Regular
	g.generateScalarEncodeTS("msg."+fieldName, fieldNum, field.Type, "    ")
}

func (g *Generator) generateScalarEncodeTS(varName string, fieldNum uint32, t ast.FieldType, indent string) {
	switch t.Kind {
	case ast.TypeBool:
		g.printf("%senc.writeBool(%d, %s);\n", indent, fieldNum, varName)
	case ast.TypeInt32, ast.TypeEnum:
		g.printf("%senc.writeInt32(%d, %s);\n", indent, fieldNum, varName)
	case ast.TypeInt64:
		g.printf("%senc.writeInt64(%d, %s);\n", indent, fieldNum, varName)
	case ast.TypeUint32:
		g.printf("%senc.writeUint32(%d, %s);\n", indent, fieldNum, varName)
	case ast.TypeUint64:
		g.printf("%senc.writeUint64(%d, %s);\n", indent, fieldNum, varName)
	case ast.TypeFloat32:
		g.printf("%senc.writeFloat32(%d, %s);\n", indent, fieldNum, varName)
	case ast.TypeFloat64:
		g.printf("%senc.writeFloat64(%d, %s);\n", indent, fieldNum, varName)
	case ast.TypeString:
		g.printf("%senc.writeString(%d, %s);\n", indent, fieldNum, varName)
	case ast.TypeBytes:
		g.printf("%senc.writeBytes(%d, %s);\n", indent, fieldNum, varName)
	case ast.TypeMessage:
		g.printf("%senc.writeMessage(%d, %s.encode(%s));\n", indent, fieldNum, t.Message, varName)
	}
}

func (g *Generator) generateFieldDecodeTS(field *ast.Field) {
	fieldName := toCamelCaseTS(field.Name)
	fieldNum := field.Number

	g.printf("        case %d:\n", fieldNum)

	// Repeated
	if field.Repeated {
		g.printf("          if (!msg.%s) msg.%s = [];\n", fieldName, fieldName)
		g.generateScalarDecodeTS(fieldName, field.Type, "          ", true)
		return
	}

	// Map
	if field.Type.Kind == ast.TypeMap {
		g.printf("          {\n")
		g.printf("            const mapData = dec.readMessageBytes();\n")
		g.printf("            const mapDec = new Decoder(mapData);\n")
		g.printf("            let mk: %s;\n", tsBaseTypeName(*field.Type.KeyType))
		g.printf("            let mv: %s;\n", tsBaseTypeName(*field.Type.ValType))
		g.printf("            while (!mapDec.eof()) {\n")
		g.printf("              const [fn] = mapDec.readTag();\n")
		g.printf("              if (fn === 1) mk = %s;\n", tsReadCall(*field.Type.KeyType, "mapDec"))
		g.printf("              else if (fn === 2) mv = %s;\n", tsReadCall(*field.Type.ValType, "mapDec"))
		g.printf("            }\n")
		g.printf("            if (!msg.%s) msg.%s = new Map();\n", fieldName, fieldName)
		g.printf("            msg.%s.set(mk!, mv!);\n", fieldName)
		g.printf("          }\n")
		g.printf("          break;\n")
		return
	}

	// Regular
	g.generateScalarDecodeTS(fieldName, field.Type, "          ", false)
}

func (g *Generator) generateScalarDecodeTS(fieldName string, t ast.FieldType, indent string, isRepeated bool) {
	readExpr := tsReadCall(t, "dec")
	if isRepeated {
		g.printf("%smsg.%s.push(%s);\n", indent, fieldName, readExpr)
	} else {
		g.printf("%smsg.%s = %s;\n", indent, fieldName, readExpr)
	}
	g.printf("%sbreak;\n", indent)
}

func tsReadCall(t ast.FieldType, dec string) string {
	switch t.Kind {
	case ast.TypeBool:
		return dec + ".readBool()"
	case ast.TypeInt32, ast.TypeEnum:
		return dec + ".readInt32()"
	case ast.TypeInt64:
		return dec + ".readInt64()"
	case ast.TypeUint32:
		return dec + ".readUint32()"
	case ast.TypeUint64:
		return dec + ".readUint64()"
	case ast.TypeFloat32:
		return dec + ".readFloat32()"
	case ast.TypeFloat64:
		return dec + ".readFloat64()"
	case ast.TypeString:
		return dec + ".readString()"
	case ast.TypeBytes:
		return dec + ".readBytes()"
	case ast.TypeMessage:
		return fmt.Sprintf("%s.decode(%s.readMessageBytes())", t.Message, dec)
	default:
		return "null as any"
	}
}

func tsTypeName(field *ast.Field) string {
	t := field.Type
	base := tsBaseTypeName(t)

	if field.Repeated {
		return base + "[]"
	}
	if t.Kind == ast.TypeMap {
		return fmt.Sprintf("Map<%s, %s>", tsBaseTypeName(*t.KeyType), tsBaseTypeName(*t.ValType))
	}
	return base
}

func tsBaseTypeName(t ast.FieldType) string {
	switch t.Kind {
	case ast.TypeBool:
		return "boolean"
	case ast.TypeInt32, ast.TypeUint32, ast.TypeFloat32, ast.TypeFloat64, ast.TypeEnum:
		return "number"
	case ast.TypeInt64, ast.TypeUint64:
		return "bigint"
	case ast.TypeString:
		return "string"
	case ast.TypeBytes:
		return "Uint8Array"
	case ast.TypeMessage:
		return t.Message
	default:
		return "unknown"
	}
}

func toCamelCaseTS(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
