// Package typescript generates TypeScript code from XPB schemas.
package typescript

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/anthropic/xpb/pkg/ast"
)

// Generator generates TypeScript code from an AST.
type Generator struct {
	buf bytes.Buffer
}

// Generate generates TypeScript code for the given file AST.
func Generate(file *ast.File) ([]byte, error) {
	g := &Generator{}
	return g.generate(file)
}

func (g *Generator) generate(file *ast.File) ([]byte, error) {
	g.buf.Reset()

	g.printf("// Code generated by xpbc. DO NOT EDIT.\n\n")
	g.printf("import { Encoder, Decoder } from '@xpb/runtime';\n\n")

	// Generate enums
	for _, enum := range file.Enums {
		g.generateEnum(enum)
	}

	// Generate messages
	for _, msg := range file.Messages {
		g.generateMessage(msg)
	}

	return g.buf.Bytes(), nil
}

func (g *Generator) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) generateEnum(enum *ast.Enum) {
	name := enum.Name
	g.printf("export enum %s {\n", name)
	for _, v := range enum.Values {
		g.printf("  %s = %d,\n", v.Name, v.Number)
	}
	g.printf("}\n\n")
}

func (g *Generator) generateMessage(msg *ast.Message) {
	name := msg.Name

	// Interface
	g.printf("export interface %sData {\n", name)
	for _, field := range msg.Fields {
		tsType := tsTypeName(field)
		fieldName := toCamelCaseTS(field.Name)
		if field.Optional {
			g.printf("  %s?: %s;\n", fieldName, tsType)
		} else {
			g.printf("  %s: %s;\n", fieldName, tsType)
		}
	}
	g.printf("}\n\n")

	// Class
	g.printf("export class %s implements %sData {\n", name, name)
	for _, field := range msg.Fields {
		tsType := tsTypeName(field)
		fieldName := toCamelCaseTS(field.Name)
		if field.Optional {
			g.printf("  %s?: %s;\n", fieldName, tsType)
		} else if field.Repeated {
			g.printf("  %s: %s = [];\n", fieldName, tsType)
		} else if field.Type.Kind == ast.TypeMap {
			g.printf("  %s: %s = new Map();\n", fieldName, tsType)
		} else {
			g.printf("  %s!: %s;\n", fieldName, tsType)
		}
	}
	g.printf("\n")

	// Constructor
	g.printf("  constructor(data: Partial<%sData> = {}) {\n", name)
	g.printf("    Object.assign(this, data);\n")
	g.printf("  }\n\n")

	// Encode
	g.printf("  static encode(msg: %sData): Uint8Array {\n", name)
	g.printf("    const enc = new Encoder();\n")
	// V2: Encode fields in order, no tags
	for _, field := range msg.Fields {
		g.generateFieldEncodeTS(field)
	}
	g.printf("    return enc.finish();\n")
	g.printf("  }\n\n")

	// Decode
	g.printf("  static decode(data: Uint8Array): %s {\n", name)
	g.printf("    const dec = new Decoder(data);\n")
	g.printf("    const msg = new %s();\n", name)
	// V2: Decode fields in order, no switch/tags
	for _, field := range msg.Fields {
		g.generateFieldDecodeTS(field)
	}
	g.printf("    return msg;\n")
	g.printf("  }\n\n")

	// Instance encode
	g.printf("  encode(): Uint8Array {\n")
	g.printf("    return %s.encode(this);\n", name)
	g.printf("  }\n")

	g.printf("}\n\n")
}

func (g *Generator) generateFieldEncodeTS(field *ast.Field) {
	fieldName := toCamelCaseTS(field.Name)

	// Repeated
	if field.Repeated {
		g.printf("    enc.writeInt32(msg.%s?.length ?? 0);\n", fieldName)
		g.printf("    for (const v of msg.%s ?? []) {\n", fieldName)
		g.generateScalarEncodeTS("v", field.Type, "      ")
		g.printf("    }\n")
		return
	}

	// Map
	if field.Type.Kind == ast.TypeMap {
		g.printf("    enc.writeInt32(msg.%s?.size ?? 0);\n", fieldName)
		g.printf("    for (const [k, v] of msg.%s ?? []) {\n", fieldName)
		g.generateScalarEncodeTS("k", *field.Type.KeyType, "      ")
		g.generateScalarEncodeTS("v", *field.Type.ValType, "      ")
		g.printf("    }\n")
		return
	}

	// Regular (V2 treats optional/required same in struct mode usually,
	// but for optional we might need a presence bit or just assume defaults.
	// For now, mirroring Go: write the value directly.
	// Note: If msg.field is undefined, we need defaults to match Go zero-values)

	// Safety check for undefined
	//nolint:staticcheck
	if field.Optional {
		// TODO: V2 optional field handling not yet implemented
		// V2 treats optional/required same in struct mode
		// For now, write zero-value to maintain struct alignment
	}

	g.generateScalarEncodeTS("msg."+fieldName, field.Type, "    ")
}

func (g *Generator) generateScalarEncodeTS(varName string, t ast.FieldType, indent string) {
	// Handle undefined for required fields by assuming valid input or letting it fail/default
	// Ideally we'd use ?? defaults here if needed.

	switch t.Kind {
	case ast.TypeBool:
		g.printf("%senc.writeBool(%s);\n", indent, varName)
	case ast.TypeInt32, ast.TypeEnum:
		g.printf("%senc.writeInt32(%s);\n", indent, varName)
	case ast.TypeInt64:
		g.printf("%senc.writeInt64(BigInt(%s));\n", indent, varName)
	case ast.TypeUint32:
		g.printf("%senc.writeUint32(%s);\n", indent, varName)
	case ast.TypeUint64:
		g.printf("%senc.writeUint64(BigInt(%s));\n", indent, varName)
	case ast.TypeFloat32:
		g.printf("%senc.writeFloat32(%s);\n", indent, varName)
	case ast.TypeFloat64:
		g.printf("%senc.writeFloat64(%s);\n", indent, varName)
	case ast.TypeString:
		g.printf("%senc.writeString(%s ?? \"\");\n", indent, varName)
	case ast.TypeBytes:
		g.printf("%senc.writeBytes(%s ?? new Uint8Array(0));\n", indent, varName)
	case ast.TypeMessage:
		// V2 Message: length prefix + encoded bytes
		g.printf("%senc.writeMessage(%s.encode(%s));\n", indent, t.Message, varName)
	}
}

func (g *Generator) generateFieldDecodeTS(field *ast.Field) {
	fieldName := toCamelCaseTS(field.Name)

	// Repeated
	if field.Repeated {
		g.printf("    {\n")
		g.printf("      const count = dec.readInt32();\n")
		g.printf("      msg.%s = new Array(count);\n", fieldName)
		g.printf("      for (let i = 0; i < count; i++) {\n")
		g.generateScalarDecodeTS(fieldName, field.Type, "        ", true, false)
		g.printf("      }\n")
		g.printf("    }\n")
		return
	}

	// Map
	if field.Type.Kind == ast.TypeMap {
		g.printf("    {\n")
		g.printf("      const count = dec.readInt32();\n")
		g.printf("      msg.%s = new Map();\n", fieldName)
		g.printf("      for (let i = 0; i < count; i++) {\n")
		g.printf("        let k: %s;\n", tsBaseTypeName(*field.Type.KeyType))
		g.printf("        let v: %s;\n", tsBaseTypeName(*field.Type.ValType))

		// Read key
		g.generateScalarDecodeTS("k", *field.Type.KeyType, "        ", false, true)
		// Read value
		g.generateScalarDecodeTS("v", *field.Type.ValType, "        ", false, true)

		g.printf("        msg.%s.set(k!, v!);\n", fieldName)
		g.printf("      }\n")
		g.printf("    }\n")
		return
	}

	// Regular
	g.generateScalarDecodeTS(fieldName, field.Type, "    ", false, false)
}

func (g *Generator) generateScalarDecodeTS(target string, t ast.FieldType, indent string, isRepeated bool, isLocalVar bool) {
	readExpr := tsReadCall(t)

	lhs := ""
	if isLocalVar {
		lhs = target
	} else if isRepeated {
		lhs = fmt.Sprintf("msg.%s[i]", target)
	} else {
		lhs = fmt.Sprintf("msg.%s", target)
	}

	g.printf("%s%s = %s;\n", indent, lhs, readExpr)
}

func tsReadCall(t ast.FieldType) string {
	switch t.Kind {
	case ast.TypeBool:
		return "dec.readBool()"
	case ast.TypeInt32, ast.TypeEnum:
		return "dec.readInt32()"
	case ast.TypeInt64:
		return "dec.readInt64()"
	case ast.TypeUint32:
		return "dec.readUint32()"
	case ast.TypeUint64:
		return "dec.readUint64()"
	case ast.TypeFloat32:
		return "dec.readFloat32()"
	case ast.TypeFloat64:
		return "dec.readFloat64()"
	case ast.TypeString:
		return "dec.readString()"
	case ast.TypeBytes:
		return "dec.readBytes()"
	case ast.TypeMessage:
		return fmt.Sprintf("%s.decode(dec.readMessageBytes())", t.Message)
	default:
		return "null as any"
	}
}

func tsTypeName(field *ast.Field) string {
	t := field.Type
	base := tsBaseTypeName(t)

	if field.Repeated {
		return base + "[]"
	}
	if t.Kind == ast.TypeMap {
		return fmt.Sprintf("Map<%s, %s>", tsBaseTypeName(*t.KeyType), tsBaseTypeName(*t.ValType))
	}
	return base
}

func tsBaseTypeName(t ast.FieldType) string {
	switch t.Kind {
	case ast.TypeBool:
		return "boolean"
	case ast.TypeInt32, ast.TypeUint32, ast.TypeFloat32, ast.TypeFloat64, ast.TypeEnum:
		return "number"
	case ast.TypeInt64, ast.TypeUint64:
		return "bigint"
	case ast.TypeString:
		return "string"
	case ast.TypeBytes:
		return "Uint8Array"
	case ast.TypeMessage:
		return t.Message
	default:
		return "unknown"
	}
}

func toCamelCaseTS(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
